### ISSUE TITLE
Metrics related to send success/fail spans as well as batch

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-collector#662] opened 2020-03-19 16:25 UTC
Currently there are `otelcol_success_send` and `otelcol_fail_send` counters that record the number of batches sent by the queue processor. Would it be also possible to record the number of spans?

Jaeger reports `jaeger_agent_reporter_(batches|spans)_(submitted|failures)`, allowing identification of both the number of successful/failed batches as well as spans.

Additionally Jaeger has a gauge `jaeger_agent_reporter_batch_size` - would it be worth adding something similar in the queue processor to report on the batch sizes being processed?

**Comment by pjanotti** [comment] 2020-03-19 18:56
@objectiser we are in the process of changing the metrics of the Collector an initial part of that work was recently merged. The new metrics have `otelcol_exporter_sent_spans` and `otelcol_exporter_send_failed_spans` for the exporters. That should give the visibility for the number of spans sent to Jaeger (check the exporter label). Currently, there is no aggregation to get number of batches directly from these metrics.

```terminal
# HELP otelcol_exporter_send_failed_spans Number of spans in failed attempts to send to destination.
# TYPE otelcol_exporter_send_failed_spans counter
otelcol_exporter_send_failed_spans{exporter="jaeger_grpc"} 0
# HELP otelcol_exporter_sent_metric_points Number of metric points successfully sent to destination.
# HELP otelcol_exporter_sent_spans Number of spans successfully sent to destination.
# TYPE otelcol_exporter_sent_spans counter
otelcol_exporter_sent_spans{exporter="jaeger_grpc"} 1773
```

The number of batches, for now, you can take from the `queued_retry` processor as you figured out, notice that this processor is part of the recommended configuration. The new metric to identify drops by a processor is `otelcol_processor_dropped_spans`

For size some experiments indicated a high cost to obtain that from OC (via proto package iirc), that said I think we have an opportunity to get the size at a lower cost with the new internal format.

**Comment by objectiser** [comment] 2020-03-20 14:40
@pjanotti Thanks for the info. The current batch metrics also have the `service` dimension - would it make sense to also have it for these span based counters?

**Comment by bogdandrutu** [comment] 2020-08-04 00:42
The missing part is "service", but it is pretty expensive to log service all the time especially when batch multiple "spans" from different services.

@objectiser is this a blocker for you?

**Comment by bogdandrutu** [comment] 2020-08-04 00:46
Closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/857

**Closed by bogdandrutu** 2020-08-04 00:46 UTC
