### ISSUE TITLE
logging exporter don't see metric examplar

### ISSUE THREAD

**Issue by oliver-zhang** [open-telemetry/opentelemetry-collector#8087] opened 2023-07-13 06:53 UTC
**Describe the bug**
I can see mertric exemplars via otel sdk logging exporter, but i don’t see exemplars via collector logger exporter,

**Steps to reproduce**
Using java auto instrumentation, set otel.metrics.exporter=otlp and otel.exporter.otlp.metrics.endpoint=http://otel-col:4317

**What did you expect to see?**
I want to see metric exemplar from logging exporter

**What did you see instead?**
I don't see metric examplar

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
service：
  pipelines:
    metrics:
      receivers: otlp
      processors: []
      exporters: logging

**Comment by mx-psi** [comment] 2023-07-13 08:36
Thanks for the report! I believe this is a duplicate of #7912, can you upvote that issue instead?

**Closed by mx-psi** 2023-07-13 08:36 UTC
Labels: bug
