### ISSUE TITLE
Should be buffer between SDK and Collector, such as file system and kafka?

### ISSUE THREAD

**Issue by govine** [open-telemetry/opentelemetry-collector#2351] opened 2021-01-11 06:31 UTC
As we can see from the SDK source code:
https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/trace/batch_span_processor.go
If the Collector is blocked, it will cause the data collected by the SDK to be lost or cause the application to block.
Perhaps a reasonable approach is to use the file system as a cache on the SDK side.
Then use some log collection tools, such as filebeat, to collect the data to Kafka.
Then Collector consumes Kafka's data.
Deploying Collector and business server on the same machine is also an unreasonable option.
Because Collector is likely to seize some of the CPU resources.

**Comment by tigrannajaryan** [comment] 2021-01-14 14:58
Duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/2285
Please comment on that other issue.

**Closed by tigrannajaryan** 2021-01-14 14:58 UTC
Labels: question
