### ISSUE TITLE
Send logs to stdout instead of stderr

### ISSUE THREAD

**Issue by sefaYavuz** [open-telemetry/opentelemetry-collector#7554] opened 2023-04-20 08:03 UTC
**Describe the bug**
I'm using the OpenTelemetry Operator and i'm trying to send the logs of the agent to stdout instead of stderr. Because our product runs on GCP, every log entry provided by the agent get's marked as an error. 

I've found that you could change this by setting this property: `-Dio.opentelemetry.javaagent.slf4j.simpleLogger.logFile=System.Out`

But this doesn't work.

**Steps to reproduce**

To the OpenTelemetryCollector CR I pass the env `JAVA_TOOL_OPTIONS` with the value `-Dio.opentelemetry.javaagent.slf4j.simpleLogger.logFile=System.Out`

```
manifest = {
    "apiVersion" = "opentelemetry.io/v1alpha1"
    "kind" = "OpenTelemetryCollector"
    "metadata" = {
      "name" = "default"
      "namespace" = "default"
    }
    "spec" = {
      "env" = [{
        name = "JAVA_TOOL_OPTIONS"
        value = "-Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=off"
      }]
      "mode" = "deployment"
      "serviceAccount" = "k8-sa"
      "config" = ""
  }
}
```

I'm using terraform to create this.

**What did you expect to see?**
Logs to appear as their level on GCP.

**What did you see instead?**
Logs in error severity in GCP.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/7534379/233061605-926b9363-18b6-42dc-8354-8b4a01db07b1.png">

**What version are you using?**
open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0

**Comment by JaredTan95** [comment] 2023-04-24 02:11
@sefaYavuz Could you pls move this issue into `open-telemetry/opentelemetry-operator` repo?

**Comment by sefaYavuz** [comment] 2023-04-24 07:37
@JaredTan95 Already did, they told me to open up an issue in this repo. See: [#8318](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8318)

**Comment by atoulme** [comment] 2023-04-24 21:32
There is no relationship to the Java SDK here. This collector is built with Golang and runs as an executable processor in its own pod. The collector by default outputs logs to stderr. I think you are looking for an enhancement allowing the collector to run as stdout.

**Comment by sefaYavuz** [comment] 2023-04-26 10:05
> There is no relationship to the Java SDK here. This collector is built with Golang and runs as an executable processor in its own pod. The collector by default outputs logs to stderr. I think you are looking for an enhancement allowing the collector to output to stdout.

Hmm, isn't there an easy way to fix this?

**Comment by atoulme** [comment] 2023-05-05 18:32
Before we move to solutioning, please confirm this is indeed the problem you are encountering.

**Comment by sefaYavuz** [comment] 2023-05-08 06:32
> Before we move to solutioning, please confirm this is indeed the problem you are encountering.

Well yeah, the problem remains the same. The output is to stderr, which needs to go stdout.

**Comment by alexchowle** [comment] 2024-02-26 11:51
I agree - to write all logs to StdErr is sub-optimal.

**Comment by rally25rs** [comment] 2024-03-06 14:30
This is probably a duplicate of #3460

And I agree writing to `stderr` seems like an unfortunate choice. Pretty much every other tool in the chain (k8s, datadog, openobserve, loki, etc...) assumes output to `stderr` is an "error" so trying to set up alerts on "errors" metrics gets hard.

**Comment by codeboten** [comment] 2024-04-25 19:35
Thanks for all the comments. Closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/3460 to try and reduce the number of places where the discussion is happening, please comment on that issue.

**Closed by codeboten** 2024-04-25 19:35 UTC
Labels: bug
