### ISSUE TITLE
slf4j (logback) logs not getting forwarded to open-telemetry-collector

### ISSUE THREAD

**Issue by ff-sdesai** [open-telemetry/opentelemetry-collector#7008] opened 2023-01-24 10:38 UTC
I have created a spring-boot micro-service with spring-cloud-sleuth. I have also configured a open-telemetry-collector to forward the logs to datadog. The otel-collector is running in a docker container along with the micro-service. I have used logback-appender to forward the logs also to otel-collector along with traces. However, in datadog, I can only see traces and not logs. The logs printed are using the same traceId and spanId as that of trace. But due to some unknown reason, otel-collector is not exporting logs like it is exporting traces.

This issue can be reproduced using a POC with very few files and is uploaded at [https://github.com/ff-sdesai/distributed-tracing-spring](https://github.com/ff-sdesai/distributed-tracing-spring). The readme.md has the steps to run the application. You will need to enter a valid datadog API key in the .env (hidden) file.I will not be able to share the key since the key is specific to my organization.  
Please let me know if there is something else that I should specify along with these details.

I am using docker image otel/opentelemetry-collector-contrib:0.69.0 and Ubuntu 22.04.1 LTS

**Comment by jpkrohling** [comment] 2023-01-24 12:35
Can you please check the collector metrics, to ensure it's actually receiving log data? You seem to be using the logging exporter as well: did you see anything printed in the console that would help confirm you received logs from your application?

**Comment by noamisr** [comment] 2023-01-24 12:44
Hey :)

not sure if i should open a new issue but I'm experiencing the same effect with a simple `otlp.http` receiver and a curl test.

I'm using the latest collector-contrib with this configuration:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: "debug"

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]
``` 

When I make a post to the `/v1/logs` endpoint, the otel http server returns:
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 24 Jan 2023 12:32:12 GMT
Content-Length: 21

{"partialSuccess":{}}
```

And when looking at the collector's logs, nothing happens.

**Comment by ff-sdesai** [comment] 2023-01-24 12:54
> Can you please check the collector metrics, to ensure it's actually receiving log data? You seem to be using the logging exporter as well: did you see anything printed in the console that would help confirm you received logs from your application?

Yes. I can see the log on the docker console and the log is using same trace_id and span_id as the trace

**Comment by ff-sdesai** [comment] 2023-01-24 12:55
> Hey :)
> 
> not sure if i should open a new issue but I'm experiencing the same effect with a simple `otlp.http` receiver and a curl test.
> 
> I'm using the latest collector-contrib with this configuration:
> 
> ```
> receivers:
>   otlp:
>     protocols:
>       grpc:
>       http:
> 
> exporters:
>   logging:
>     loglevel: "debug"
> 
> service:
>   telemetry:
>     logs:
>       level: "debug"
>   pipelines:
>     logs:
>       receivers: [otlp]
>       processors: []
>       exporters: [logging]
> ```
> 
> When I make a post to the `/v1/logs` endpoint, the otel http server returns:
> 
> ```
> HTTP/1.1 200 OK
> Content-Type: application/json
> Date: Tue, 24 Jan 2023 12:32:12 GMT
> Content-Length: 21
> 
> {"partialSuccess":{}}
> ```
> 


> Hey :)
> 
> not sure if i should open a new issue but I'm experiencing the same effect with a simple `otlp.http` receiver and a curl test.
> 
> I'm using the latest collector-contrib with this configuration:
> 
> ```
> receivers:
>   otlp:
>     protocols:
>       grpc:
>       http:
> 
> exporters:
>   logging:
>     loglevel: "debug"
> 
> service:
>   telemetry:
>     logs:
>       level: "debug"
>   pipelines:
>     logs:
>       receivers: [otlp]
>       processors: []
>       exporters: [logging]
> ```
> 
> When I make a post to the `/v1/logs` endpoint, the otel http server returns:
> 
> ```
> HTTP/1.1 200 OK
> Content-Type: application/json
> Date: Tue, 24 Jan 2023 12:32:12 GMT
> Content-Length: 21
> 
> {"partialSuccess":{}}
> ```
> 
> And when looking at the collector's logs, nothing happens.

How can I post any log directly at the otel-collector ? Is there any reference documentation?

**Comment by noamisr** [comment] 2023-01-24 13:09
> > Hey :)
> > not sure if i should open a new issue but I'm experiencing the same effect with a simple `otlp.http` receiver and a curl test.
> > I'm using the latest collector-contrib with this configuration:
> > ```
> > receivers:
> >   otlp:
> >     protocols:
> >       grpc:
> >       http:
> > 
> > exporters:
> >   logging:
> >     loglevel: "debug"
> > 
> > service:
> >   telemetry:
> >     logs:
> >       level: "debug"
> >   pipelines:
> >     logs:
> >       receivers: [otlp]
> >       processors: []
> >       exporters: [logging]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I make a post to the `/v1/logs` endpoint, the otel http server returns:
> > ```
> > HTTP/1.1 200 OK
> > Content-Type: application/json
> > Date: Tue, 24 Jan 2023 12:32:12 GMT
> > Content-Length: 21
> > 
> > {"partialSuccess":{}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And when looking at the collector's logs, nothing happens.
> 
> How can I post any log directly at the otel-collector ? Is there any reference documentation?

(From the otlp receiver docs)[https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#writing-with-httpjson] 

I already use the filelog receiver to collect local cluster logs, and want to do the same with the otlp api

**Comment by jpkrohling** [comment] 2023-01-24 14:29
Can you please check the collector metrics? I would appreciate it if you could share your metrics here.

**Comment by ff-sdesai** [comment] 2023-01-24 14:53
> Can you please check the collector metrics? I would appreciate it if you could share your metrics here.

How to check the collector metrics? Can you please share the steps?

**Comment by noamisr** [comment] 2023-01-24 17:36
> > Can you please check the collector metrics? I would appreciate it if you could share your metrics here.
> 
> How to check the collector metrics? Can you please share the steps?

You can add config for the collector, like this:

```
service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8888
```

and go to `localhost:8888/metrics`

**Comment by ff-sdesai** [comment] 2023-01-25 05:52
> > > Can you please check the collector metrics? I would appreciate it if you could share your metrics here.
> > 
> > 
> > How to check the collector metrics? Can you please share the steps?
> 
> You can add config for the collector, like this:
> 
> ```
> service:
>   telemetry:
>     metrics:
>       level: detailed
>       address: 0.0.0.0:8888
> ```
> 
> and go to `localhost:8888/metrics`

I did these steps. However, as per my web browser, there is nothing at `localhost:8888/metrics`. I also tried replacing localhost by docker container's IP address, but still same result

**Comment by ff-sdesai** [comment] 2023-01-25 06:33
> > > > Can you please check the collector metrics? I would appreciate it if you could share your metrics here.
> > > 
> > > 
> > > How to check the collector metrics? Can you please share the steps?
> > 
> > 
> > You can add config for the collector, like this:
> > ```
> > service:
> >   telemetry:
> >     metrics:
> >       level: detailed
> >       address: 0.0.0.0:8888
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and go to `localhost:8888/metrics`
> 
> I did these steps. However, as per my web browser, there is nothing at `localhost:8888/metrics`. I also tried replacing localhost by docker container's IP address, but still same result.
> 
> As per the documentation,
> 
> > Prometheus metrics are exposed locally on port 8888 and path /metrics. For containerized environments it may be desirable to expose this port on a public interface instead of just locally.
> 
> How to expose the port on a public interface?

Never mind.. I was able to reach metrics by configuring the docker's IP address in the config file

**Comment by MovieStoreGuy** [comment] 2023-01-26 11:46
Just to follow up, is this still a problem @ff-sdesai ?

**Comment by ff-sdesai** [comment] 2023-01-26 12:23
> Just to follow up, is this still a problem @ff-sdesai ?

Yes. Haven't got any solution yet

**Comment by evan-bradley** [comment] 2023-01-26 19:44
Hi @ff-sdesai, thanks for providing a minimal reproduction setup. I ran it on my machine and wasn't able to confirm that the Collector was receiving any log records. Have you been able to verify that the log records are being exported from your application?

**Comment by ff-sdesai** [comment] 2023-01-27 04:42
> Hi @ff-sdesai, thanks for providing a minimal reproduction setup. I ran it on my machine and wasn't able to confirm that the Collector was receiving any log records. Have you been able to verify that the log records are being exported from your application?

Hi @evan-bradley , how can I confirm that the collector is receiving the log from the application? Is there any information that I should be looking at in the logs?

**Comment by ff-sdesai** [comment] 2023-01-27 04:52
> Hi @ff-sdesai, thanks for providing a minimal reproduction setup. I ran it on my machine and wasn't able to confirm that the Collector was receiving any log records. Have you been able to verify that the log records are being exported from your application?

Hi @evan-bradley , how can I confirm that the collector is receiving the log from the application? Is there any information that I should be looking at in the logs?Also, is there a way to manually send the logs to otel-collector? Where can I get the sample logs in the expected format for this?

**Comment by jpkrohling** [comment] 2023-01-30 13:01
This might be related to #7009

**Comment by jpkrohling** [comment] 2023-01-30 17:05
I just tried your application, and I can't figure out how your signals.json is being populated. I was able to get trace data received by the collector, but apparently, there's nothing sending log data to the collector. 

In your collector config, I see you configured a file receiver getting logs from /tmp/signals.json, but there's nothing writing logs to that.

Fow now, I'm closing this, but once you provide me with more information, I'll reopen and take another look.

**Comment by ff-sdesai** [comment] 2023-01-31 05:18
> I just tried your application, and I can't figure out how your signals.json is being populated. I was able to get trace data received by the collector, but apparently, there's nothing sending log data to the collector.
> 
> In your collector config, I see you configured a file receiver getting logs from /tmp/signals.json, but there's nothing writing logs to that.
> 
> Fow now, I'm closing this, but once you provide me with more information, I'll reopen and take another look.

@jpkrohling  I am new to this. So can you please explain some more details to me?
I have configured exporters.file.path to /tmp/signals.json. As you pointed out, no component is writing explicitly to this path. But still, traces are getting forwarded to datadog. So, is there any reason logs are not forwarded like traces? file.path configuration is independent of type being traces or logs, isn't it?

**Comment by jpkrohling** [comment] 2023-01-31 12:15
Traces are not logs. You have your slf4j configured and it will print out log lines with the trace ID and span ID for the current request, but you'd have to write the logs to a file, which will then be read by the OpenTelemetry Collector. Or use a log appender that writes directly to the OTLP Logs port of the collector. Right now, your logs are being written to the console and are not being collected by anything.

**Comment by ff-sdesai** [comment] 2023-01-31 12:51
> Traces are not logs. You have your slf4j configured and it will print out log lines with the trace ID and span ID for the current request, but you'd have to write the logs to a file, which will then be read by the OpenTelemetry Collector. Or use a log appender that writes directly to the OTLP Logs port of the collector. Right now, your logs are being written to the console and are not being collected by anything.

@jpkrohling  If you check , I have already added a otel-appender using following block of code:-
```
<appender name="OTEL" class="io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender">
        <appender-ref ref="STDOUT" />
    </appender>
```
It is supposed to append the logs to the otel-collector. Can you please check if I am still missing any configuration in this logback.xml?

**Comment by jpkrohling** [comment] 2023-01-31 13:05
I'm not the right person to answer this question, but isn't it just adding this to the console (stdout) instead of a file?

**Comment by ff-sdesai** [comment] 2023-01-31 13:09
> I'm not the right person to answer this question, but isn't it just adding this to the console (stdout) instead of a file?

OpenTelemetryAppender is referring to the logs printed on Console. 
Also, I tried sending the logs directly also using curl to otel-collector. The logs were still not printed.

**Comment by jpkrohling** [comment] 2023-01-31 13:12
Can you provide me the exact curl command you used?

**Comment by ff-sdesai** [comment] 2023-01-31 13:19
> Can you provide me the exact curl command you used?

 `curl -i http://localhost:4318/v1/logs -X POST -H "Content-Type: application/json" -d @/home/sdesai/Desktop/otel/logs.json`

logs.json content is as following:-

`{"resourceLogs":[{"resource":{"attributes":[{"key":"resource-attr","value":{"stringValue":"resource-attr-val-1"}}]},"instrumentationLibraryLogs":[{"instrumentationLibrary":{},"logs":[{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","name":"logA","body":{"stringValue":"This is a log message"},"attributes":[{"key":"app","value":{"stringValue":"server"}},{"key":"instance_num","value":{"intValue":"1"}}],"droppedAttributesCount":1,"traceId":"08040201000000000000000000000000","spanId":"0102040800000000"},{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","name":"logB","body":{"stringValue":"something happened"},"attributes":[{"key":"customer","value":{"stringValue":"acme"}},{"key":"env","value":{"stringValue":"dev"}}],"droppedAttributesCount":1,"traceId":"","spanId":""}]}]}]}`

**Comment by ff-sdesai** [comment] 2023-01-31 13:36
And the response for above curl is :-

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   859  100    21  100   838   4054   158k --:--:-- --:--:-- --:--:--  167k
bash: HTTP/1.1: No such file or directory
```

**Comment by jpkrohling** [comment] 2023-01-31 18:12
I just debugged your curl call and the problem is with the payload. Apparently, there's a doc issue from the place you obtained those log entries and I'll fix that soon. I could not find a problem with the OTLP receiver though.

Here's the payload I used for the test:

```json
{
    "resourceLogs": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "resource-attr",
                        "value": {
                            "stringValue": "resource-attr-val-1"
                        }
                    }
                ]
            },
            "scopeLogs": [
                {
                    "scope": {},
                    "logRecords": [
                        {
                            "timeUnixNano": "1581452773000000789",
                            "severityNumber": 9,
                            "severityText": "Info",
                            "name": "logA",
                            "body": {
                                "stringValue": "This is a log message"
                            },
                            "attributes": [
                                {
                                    "key": "app",
                                    "value": {
                                        "stringValue": "server"
                                    }
                                },
                                {
                                    "key": "instance_num",
                                    "value": {
                                        "intValue": "1"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 1,
                            "traceId": "08040201000000000000000000000000",
                            "spanId": "0102040800000000"
                        },
                        {
                            "timeUnixNano": "1581452773000000789",
                            "severityNumber": 9,
                            "severityText": "Info",
                            "name": "logB",
                            "body": {
                                "stringValue": "something happened"
                            },
                            "attributes": [
                                {
                                    "key": "customer",
                                    "value": {
                                        "stringValue": "acme"
                                    }
                                },
                                {
                                    "key": "env",
                                    "value": {
                                        "stringValue": "dev"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 1,
                            "traceId": "",
                            "spanId": ""
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Closed by jpkrohling** 2023-01-31 18:12 UTC
Labels: bug, question

**Comment by ff-sdesai** [comment] 2023-02-01 12:22
@jpkrohling  I tried payload you mentioned and I am getting following error:-
```
curl -i http://localhost:4318/v1/logs -X POST -H "Content-Type: application/json" -d @/home/sdesai/Desktop/otel/logs_new.json
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Wed, 01 Feb 2023 12:21:35 GMT
Content-Length: 186

{"code":3,"message":"ReadObjectCB: expect { or n, but found I, error found in #1 byte of ...|I just debu|..., bigger context ...|I just debugged your curl call and the problem is w|..."}
```
