### ISSUE TITLE
collector runtime metrics

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-collector#11714] opened 2024-11-20 06:42 UTC
I want to see the collector's gc and config monitoring, but I can't seem to find the definition of the relevant metrics, what I should do. thanks.

**Comment by dmathieu** [comment] 2024-11-20 08:46
These metrics are not currently available.
Closing as a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/2155

**Closed by dmathieu** 2024-11-20 08:46 UTC
