### ISSUE TITLE
Bug report for failed CircleCI build (job: loadtest)

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#2354] opened 2021-01-11 17:12 UTC
Auto-generated report for `loadtest` job build.

Link to failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/59928

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/MemoryLimit

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

**Comment by owais** [comment] 2021-01-13 18:57
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/60229

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/MemoryLimit

**Comment by owais** [comment] 2021-01-26 21:03
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/61598

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/MemoryLimit

**Comment by owais** [comment] 2021-01-28 19:05
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/61840

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/NoMemoryLimit
-  TestTraceNoBackend10kSPS/MemoryLimit

**Comment by owais** [comment] 2021-02-04 15:27
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/62232

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/NoMemoryLimit
-  TestTraceNoBackend10kSPS/MemoryLimit

**Comment by jpkrohling** [comment] 2021-06-03 07:11
Duplicate of #2911

**Closed by jpkrohling** 2021-06-03 07:11 UTC
Labels: bug, priority:p3, release:after-ga, spec:trace
