### ISSUE TITLE
Investigate if we can avoid exposing Viper in our public APIs (maybe helper for Viper if really needed)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2651] opened 2021-03-10 01:02 UTC
As we identified Viper has a lot of issues like https://github.com/open-telemetry/opentelemetry-collector/issues/2594 or funcs that we copied and changed to avoid bugs in the library.

There are multiple options including declaring our own "ConfigParser" interface backed by Viper implementation.

**Comment by tigrannajaryan** [comment] 2021-03-11 20:48
Short term
- Hide Viper in our API.

Some Long-term Options:
- Fork viper and make it case sensitive
- Wait for viper to have this fix (likely not an option given how long this has been known issue)
- Use a different YAML library

**Comment by bogdandrutu** [comment] 2021-03-11 22:18
@tigrannajaryan we also have the problem with delimiters because we want to support "." in our keys and some of the methods in viper are not updated to use the new delimiter they added, and bunch of other issues.

**Comment by tigrannajaryan** [comment] 2021-03-22 21:17
@bogdandrutu I have been playing with https://github.com/go-yaml/yaml and it seems to work nicely. I am not sure if there is anything that we need from Viper that is not handled by https://github.com/go-yaml/yaml

The unfortunate part is that likely we need to change all "mapstructure" tags to "yaml" (unless there is a way to change https://github.com/go-yaml/yaml to use "mapstructure" instead).

**Comment by knadh** [comment] 2021-03-26 07:14
@tigrannajaryan just stumbled upon this thread. koanf is a lightweight wrapper into which YAML plugs in. Handy when you'd want to merge config from other sources like command line flags.

You don't have to replace "mapstructure" with a different tag either:

`k.UnmarshalWithConf("key_to_unmarshal", &structToUnmarshal, koanf.UnmarshalConf{Tag: "mapstructure"})`

**Comment by tigrannajaryan** [comment] 2021-03-26 14:46
Thanks @knadh, that's good to know. koanf is already on our list of libraries to check out.

**Comment by rakyll** [comment] 2021-04-24 02:50
Can we follow an approach the collector used to us? Each component can take a []byte as the config and parse its own section. See https://github.com/open-telemetry/opentelemetry-collector/commit/aa5bd1aecaab807cb2eaeec231745a42acc1fa86#diff-4d58ead58d0a916d49b4ba6464c1fdaa57de835a3ab337ec26579e8dda521512R36 for the earlier approach. We used https://gopkg.in/yaml.v2 (https://github.com/go-yaml/yaml) back then.

**Comment by mx-psi** [comment] 2021-05-05 17:38
I think we are no longer exposing Viper on the public API anywhere and so this issue is now a sort-of duplicate of #2594. 

I want to work on the general issue (fixing case-sensitivity when unmarshaling) but I am not sure what the next step would be here. Would trying out the yaml/koanf packages and documenting any issues with switching to those help? Are there any other Viper issues that a new implementation should aim to fix too? 

cc @tigrannajaryan since he has tried out the yaml package and can maybe share some more concrete thoughts on this.

**Comment by alolita** [comment] 2021-05-12 02:00
@bogdandrutu is this done? Can this issue be closed?

**Comment by bogdandrutu** [comment] 2021-05-14 17:11
I made all changes to not expose Viper, everything works using the new "Parser" from config.

**Closed** 2021-05-14 17:10 UTC
Labels: area:config, help wanted
