### ISSUE TITLE
otel collector telemetry metrics server won't spawn again after restarting

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector#5084] opened 2022-03-24 20:44 UTC
**Describe the bug**
When the collector is shutdown and run again(or another collector is run again), the telemetry metrics server won't spawn again. 
- collector telemetry is shut down [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L277) when shutdown is called
- when collector is run telemetry is init [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L246)
- the telemetry init implementation only [initialize this once](https://github.com/open-telemetry/opentelemetry-collector/blob/1b7618728835aca5591221b23e92d91ad43f1905/service/telemetry.go#L84)

**Steps to reproduce**
- create a otel collector
- call Run with settings
- call shutdown
- create another otel collector
- call Run with new settings
- metrics server won't spawn again

**What did you expect to see?**
When a new collector is run again. metrics server should still be spawned

**What did you see instead?**
metrics server no longer spawns due to initOnce call.

**What version did you use?**
Version: v0.46.0

**What config did you use?**
Any valid config

**Environment**
OS: macOS catalina
Compiler(if manually compiled): go 1.17.3

**Additional context**

**Comment by tigrannajaryan** [comment] 2022-03-24 21:06
>call shutdown
Are you calling [Shutdown](https://github.com/open-telemetry/opentelemetry-collector/blob/cb868e20c8ffc616c7ca84c68834bb3bdeab82c3/service/collector.go#L128)? As far as I remember that puts the Service in a terminal state. It is not expected that Run will work again after that.

More importantly, why are you doing this? If you want to reload the Service with new config you need to use the [ConfigProvider.Watch](https://github.com/open-telemetry/opentelemetry-collector/blob/cb868e20c8ffc616c7ca84c68834bb3bdeab82c3/service/config_provider.go#L46) capability.

**Comment by splunkericl** [comment] 2022-03-24 21:11
Even if we use the watch method, the internal implementation for watch is similar. See: https://github.com/open-telemetry/opentelemetry-collector/blob/cb868e20c8ffc616c7ca84c68834bb3bdeab82c3/service/collector.go#L162-L165

It would invoke the shutdown function and then Run with the new settings.

**Comment by tigrannajaryan** [comment] 2022-03-24 21:19
> It would invoke the shutdown function and then Run with the new settings.

OK, this looks like a legitimate bug in that case. 

In any case I do not think we support calling Run after Shutdown right now. If you do that it may break in the future. I would advise to either use the watch approach or if you need Run to work after Shutdown we need a justification for that and we need to prescribe it in the contract of Service API and have tests that verify it.

Either way we need to fix this bug. We need to make sure telemetry works after a legitimate restart of the Service.

**Comment by TylerHelmuth** [comment] 2022-04-05 21:15
@tigrannajaryan do you know why Telemetry is only initialized once?  I found this TODO where the initialize is called

https://github.com/open-telemetry/opentelemetry-collector/blob/f6b1cd9d46f12c99d69b9c39d033636a3bf18b8b/service/collector.go#L222-L227

But it doesn't say why `Once` is used.

**Comment by tigrannajaryan** [comment] 2022-04-05 21:18
> @tigrannajaryan do you know why Telemetry is only initialized once? I found this TODO where the initialize is called

No, I don't know, I don't remember this part of the codebase. @bogdandrutu may know.

**Comment by TylerHelmuth** [comment] 2022-04-05 21:35
I see that the metrics server is started in a goroutine in Telemetry's initOnce, could be related to that since it doesn't appear to have a clean shutdown.

**Comment by Aneurysm9** [comment] 2022-04-05 23:56
It may have related to the use of global telemetry providers as well, which is being (has been?) refactored.  Unfortunately it was this way before I started working in that area of the code and have felt a bit like it's been dragged around blindly mimicking the previous state through a few changes.  I'm wary of Chesterton's Fence-type issues, but we should be able to reason through this.

**Comment by TylerHelmuth** [comment] 2022-04-06 00:15
I'll dive deep into it and see if I can find things that would break if it was called multiple times. 

With my initial testing today I didn't see any indication that the http server goroutine is shutting down gracefully when the collector shuts down, but I need to keep testing.

**Comment by jpkrohling** [comment] 2022-04-07 12:37
> I'll dive deep into it and see if I can find things that would break if it was called multiple times.

Perhaps I'm way off here, but OpenCensus required views to be registered only once. Is that maybe the background for this?

**Comment by bogdandrutu** [comment] 2022-04-07 16:13
There are some miss understandings here:
1. This theory is wrong https://github.com/open-telemetry/opentelemetry-collector/issues/5084#issuecomment-1078325961 because the shutdown is the "Service" shutdown, which does not stops the metrics server. So in summary you cannot reproduce this problem with watch.
2. The reason why this is global (happens once) is because we use OpenCensus (because otel metrics is not ready, we can ask one more time in that repo why and when), which uses a global that you cannot initialize twice.

There are some discussions (see https://github.com/open-telemetry/opentelemetry-collector/issues/4947) and issues to actually make it more clear that the Collector will follow the language patter for Shutdown, see http.Server.Shutdown: `When Shutdown is called, Serve, ListenAndServe, and ListenAndServeTLS immediately return ErrServerClosed.` which means you cannot call Run again.

I think we are going to the direction to follow the language pattern which is after Shutdown you cannot call Run on the same instance, you have to create a new instance.

**Comment by TylerHelmuth** [comment] 2022-04-08 17:29
Looking into this issue I agree with @bogdandrutu.  Assuming calling `Run` after `Shutdown` is not allowed, the existing outcome is acceptable.  Digging into the `Watch` scenario, the Shutdown that is called doesn't do anything with the running metrics server.  When the collector "restarts" the original telemetry instance will still be running.  I think this issue could be closed.

One interesting thing is that any new Telemetry config settings will not be honored.  If we want to be able to load new telemetry settings without a new instance of a collector I think we would need changes.  I would say thats a different issue/feature request though.

**Comment by bogdandrutu** [comment] 2022-12-14 22:57
This should be fixed now.

**Closed by bogdandrutu** 2022-12-14 22:57 UTC
Labels: bug, help wanted, priority:p1
