### ISSUE TITLE
Collector supports case insensitive configuration but it is not properly handled across the codebase.

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector#7002] opened 2023-01-23 22:16 UTC
**Describe the bug**
The collector supports case insensitive configuration, allowing typos in the configuration to change the behavior of the code. This can happen in the code because in several instances we are not relaying on the de-serialized datastructure, but checking the existing of keys in the code. 

E.g.: 
* https://github.com/open-telemetry/opentelemetry-collector/blob/2b96397073bccb68a967ca549f780a98b87c067e/exporter/loggingexporter/config.go#L75
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0801b5f3aefdf920cfda914d93d23bff14bd5778/receiver/jaegerreceiver/config.go#L157

There was a [fix](https://github.com/open-telemetry/opentelemetry-collector/pull/6876) for this issue but this was [reverted](https://github.com/open-telemetry/opentelemetry-collector/pull/6988).

**Steps to reproduce**

Create a configuration with a typo, replacing a lower case by an uppercase in the logging exporter loglevel -> logLevel.

**What did you expect to see?**
loglevel to be properly set or an error message that the configuration is invalid.

**What did you see instead?**
loglevel set incorrectly.

**What version did you use?**
v0.69.1

**Environment**
Centos 7

**Comment by rapphil** [comment] 2023-01-23 22:51
Carbon receiver already got the fix for the typo https://github.com/open-telemetry/opentelemetry-collector-contrib/blame/main/receiver/carbonreceiver/protocol/regex_parser.go#L78 which means that collector-contrib v0.70 will have this fix. after this point it is safe to change the collector validation logic to be case sensitive.

**Comment by gbbr** [comment] 2023-01-25 09:36
Thanks. I create the pull request, for when we're ready. Hope that's ok.

**Comment by bogdandrutu** [comment] 2023-01-27 17:06
The issue is correct, but there is another bug that makes it correct.

If this comment is true https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/confmap.go#L119 then this issue is not an issue, since the checks will be case-insensitive as well, but that comment is not true - Need a fix for this as well.

**Closed** 2023-01-31 19:33 UTC
Labels: bug
