### ISSUE TITLE
GRPC receiver is not supporting mTLS

### ISSUE THREAD

**Issue by ochauhan** [open-telemetry/opentelemetry-collector#4676] opened 2022-01-13 07:44 UTC
**Describe the bug**
I have chained 2 OLTP collectors with one configured as OLTP receiver with grpc and mTLS enabled. The other OLTP collector is configured as a grpc exporter. 
When I start exporting metrics using OLTP grpc exporter, it results in an error with export failing :

Error on receiver end:
	**warn	zapgrpc/zapgrpc.go:191	[core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "ServerHandshake(\"127.0.0.1:54871\") failed: remote error: tls: bad certificate"	{"grpc_log": true}**

Error on exporter end:
	**warn	zapgrpc/zapgrpc.go:191	[core] grpc: addrConn.createTransport failed to connect to {localhost:55690 localhost:55690 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"	{"grpc_log": true}**

**Steps to reproduce**
chain 2 OLTP collectors, one with grpc receiver mTLS enabled and the other with grpc exporter. 
Start exporting hostmetrics, you should start seeing warn messages with connection failing.

**What did you expect to see?**
I expected successful export but got errors

**What version did you use?**
Version: v0.42.0

**What config did you use?**
Config: 
**receiver config:**
```
receivers:
  otlp/mtls:
    protocols:
      grpc:
        endpoint: localhost:55690
        tls:
          client_ca_file: client.crt
          cert_file: server.crt
          key_file: server.key

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [ otlp/mtls ]
      exporters: [ logging ]
```

**exporter config:**
```
receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      memory:
      network:

exporters:
  otlp:
    endpoint: localhost:55690
    tls:
      insecure: false
      ca_file: server.crt
      cert_file: client.crt
      key_file: client.key
      min_version: "1.1"
      max_version: "1.2"

service:
  pipelines:
    metrics:
      receivers: [ hostmetrics ]
      exporters: [ otlp ]
```
**Environment**
OS: Mac OS BigSur

**Comment by jpkrohling** [comment] 2022-01-13 11:01
I can take a look at this, but not before next week. If anyone else wants to work on it before me, feel free to reassign.

**Comment by bogdandrutu** [comment] 2022-01-13 16:45
Naive question: how did you check that your certificates are good? (A.k.a. not bad per the log message)

**Comment by ochauhan** [comment] 2022-01-17 04:23
> Naive question: how did you check that your certificates are good? (A.k.a. not bad per the log message)

I'm using the same certificates in other services and working fine without any issue.

**Comment by wajika** [comment] 2022-01-21 01:29
I'm facing the same issue, the difference is that I don't have tls enabled.

**Comment by bogdandrutu** [comment] 2022-01-21 18:04
@wajika can you add your config please?

**Comment by ochauhan** [comment] 2022-01-27 04:38
Is anyone working on this?

**Comment by wajika** [comment] 2022-01-27 15:25
> @wajika can you add your config please?

I have solved the problem. My case is a bit different from here, but it could be similar. At first I started otel-collector without adding insecure: true, so sending a message from client to it and then forwarding it to otlp, there will be a "tls: bad certificate" error message, but I noticed that the client sent the message without stating tls configuration, then I think the collector should also not need tls communication, so adding insecure: true the problem is solved.

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:55681"
processors:
  batch:
exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: "http://192.168.51.3:8200"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

**Comment by bogdandrutu** [comment] 2022-02-02 02:31
@ochauhan does that match with your problem? 

@jpkrohling what is the status of your investigation?

**Comment by ochauhan** [comment] 2022-02-02 04:33
@bogdandrutu  If I use

**Comment by ochauhan** [comment] 2022-02-02 04:35
> @ochauhan does that match with your problem?
> Yes,  if I use  'insecure: true' It works.

**Comment by jpkrohling** [comment] 2022-02-04 09:07
It's still on my queue, I'll reopen as it's something I do want to make sure it properly works.

**Comment by jpkrohling** [comment] 2022-02-04 15:43
I was able to confirm that mTLS indeed works. Here's the config I used:

```
receivers:
  otlp/agent:
    protocols:
      grpc:

  otlp/collector:
    protocols:
      grpc:
        endpoint: localhost:5317
        tls:
          cert_file: /tmp/certs/collector.pem
          key_file: /tmp/certs/collector-key.pem
          client_ca_file:  /tmp/certs/ca.pem

processors:

exporters:
  otlp/agent:
    endpoint: localhost:5317
    tls:
      ca_file: /tmp/certs/ca.pem
      cert_file: /tmp/certs/agent.pem
      key_file: /tmp/certs/agent-key.pem

  logging/collector:

service:
  pipelines:
    traces/agent:
      receivers:
        - otlp/agent
      processors: []
      exporters:
        - otlp/agent

    traces/collector:
      receivers:
        - otlp/collector
      processors: []
      exporters:
        - logging/collector
```

Running this collector and sending a trace with the `tracegen` yields this:

```
$ otelcol --config local/mtls.yaml 
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp/collector", "datatype": "traces"}
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp/agent", "datatype": "traces"}
2022-02-04T16:30:34.373+0100    info    service/service.go:82   Starting extensions...
2022-02-04T16:30:34.373+0100    info    service/service.go:87   Starting exporters...
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:30:34.373+0100    info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:30:34.373+0100    info    service/service.go:92   Starting processors...
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:30:34.373+0100    info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:30:34.373+0100    info    service/service.go:97   Starting receivers...
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:30:34.373+0100    info    otlpreceiver/otlp.go:69 Starting GRPC server on endpoint localhost:5317 {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:30:34.373+0100    warn    zapgrpc/zapgrpc.go:191  [core] grpc: addrConn.createTransport failed to connect to {localhost:5317 localhost:5317 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:5317: connect: connection refused"      {"grpc_log": true}
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    otlpreceiver/otlp.go:69 Starting GRPC server on endpoint 0.0.0.0:4317   {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:30:34.373+0100    info    service/telemetry.go:95 Setting up own telemetry...
2022-02-04T16:30:34.387+0100    info    service/telemetry.go:115        Serving Prometheus metrics      {"address": ":8888", "level": "basic", "service.instance.id": "f85e9f5e-25e0-403f-80a6-d17e1cd83cb3", "service.version": "latest"}
2022-02-04T16:30:34.387+0100    info    service/collector.go:229        Starting otelcol...     {"Version": "0.43.0", "NumCPU": 16}
2022-02-04T16:30:34.387+0100    info    service/collector.go:124        Everything is ready. Begin running and processing data.
2022-02-04T16:30:38.291+0100    INFO    loggingexporter/logging_exporter.go:40  TracesExporter  {"#spans": 2}
```

Using another CA in the client_ca causes this, proving that the auth was performed during the test above

```
$ otelcol --config local/mtls.yaml 
2022-02-04T16:32:28.644+0100    info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:32:28.645+0100    info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:32:28.645+0100    info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp/collector", "datatype": "traces"}
2022-02-04T16:32:28.645+0100    info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp/agent", "datatype": "traces"}
2022-02-04T16:32:28.645+0100    info    service/service.go:82   Starting extensions...
2022-02-04T16:32:28.645+0100    info    service/service.go:87   Starting exporters...
2022-02-04T16:32:28.645+0100    info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:32:28.645+0100    info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "logging/collector"}
2022-02-04T16:32:28.645+0100    info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:32:28.645+0100    info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "otlp/agent"}
2022-02-04T16:32:28.645+0100    info    service/service.go:92   Starting processors...
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "traces/collector"}
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:32:28.645+0100    info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "traces/agent"}
2022-02-04T16:32:28.645+0100    info    service/service.go:97   Starting receivers...
2022-02-04T16:32:28.645+0100    info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:32:28.645+0100    info    otlpreceiver/otlp.go:69 Starting GRPC server on endpoint localhost:5317 {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:32:28.645+0100    warn    zapgrpc/zapgrpc.go:191  [core] grpc: addrConn.createTransport failed to connect to {localhost:5317 localhost:5317 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:5317: connect: connection refused"      {"grpc_log": true}
2022-02-04T16:32:28.645+0100    info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp/collector"}
2022-02-04T16:32:28.646+0100    info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:32:28.646+0100    info    otlpreceiver/otlp.go:69 Starting GRPC server on endpoint 0.0.0.0:4317   {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:32:28.646+0100    info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp/agent"}
2022-02-04T16:32:28.646+0100    info    service/telemetry.go:95 Setting up own telemetry...
2022-02-04T16:32:28.659+0100    info    service/telemetry.go:115        Serving Prometheus metrics      {"address": ":8888", "level": "basic", "service.instance.id": "caea2970-a4d6-4ec9-af76-8350f2ef9588", "service.version": "latest"}
2022-02-04T16:32:28.659+0100    info    service/collector.go:229        Starting otelcol...     {"Version": "0.43.0", "NumCPU": 16}
2022-02-04T16:32:28.659+0100    info    service/collector.go:124        Everything is ready. Begin running and processing data.
2022-02-04T16:32:32.816+0100    warn    zapgrpc/zapgrpc.go:191  [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "ServerHandshake(\"127.0.0.1:44418\") failed: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"OpenTelemetry Collector\")"  {"grpc_log": true}
2022-02-04T16:32:32.816+0100    warn    zapgrpc/zapgrpc.go:191  [core] grpc: addrConn.createTransport failed to connect to {localhost:5317 localhost:5317 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"       {"grpc_log": true}
2022-02-04T16:32:32.816+0100    info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "otlp/agent", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: remote error: tls: bad certificate\"", "interval": "5.52330144s"}
2022-02-04T16:32:38.353+0100    warn    zapgrpc/zapgrpc.go:191  [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "ServerHandshake(\"127.0.0.1:44420\") failed: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"OpenTelemetry Collector\")"  {"grpc_log": true}
```

This is how the certs were generated:

```
cfssl genkey -initca /tmp/certs/ca-csr.json | cfssljson -bare ca

# collector, server side
cfssl gencert -ca ca.pem -ca-key ca-key.pem -config /tmp/certs/cfssl.json -profile=server collector-csr.json | cfssljson -bare collector

# agent, client side
cfssl gencert -ca ca.pem -ca-key ca-key.pem -config /tmp/certs/cfssl.json -profile=client agent-csr.json | cfssljson -bare agent

$ cat ca-csr.json 
{
    "hosts": [
        "localhost",
        "127.0.0.1"
    ],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "O": "OpenTelemetry Collector"
        }
    ]
}

$ cat cfssl.json
{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "server": {
        "usages": [
          "signing",
          "digital signing",
          "key encipherment",
          "server auth"
        ],
        "expiry": "8760h"
      },
      "client": {
        "usages": [
          "signing",
          "digital signature",
          "key encipherment",
          "client auth"
        ],
        "expiry": "8760h"
      }
    }
  }
}
```

**Closed by jpkrohling** 2022-02-04 15:43 UTC
Labels: bug
