### ISSUE TITLE
Receiver Start function not invoked sometimes for flows

### ISSUE THREAD

**Issue by Ishmeet** [open-telemetry/opentelemetry-collector#8131] opened 2023-07-25 08:24 UTC
**Describe the bug**
In my config I have a custom receivers created for traces, metrics and logs. On running the otel-collector binary, sometimes I don't see the Start method getting executed for logs but for metrics it executes. This is happening intermittently, sometimes on killing the binary and re-running it, all receivers Start method executes. Sometimes traces are missing sometimes logs.  

**Steps to reproduce**
Run same binary multiple times, and see if all receivers starts.

**What did you expect to see?**
On every time running the Otel collector binary, all metrics/traces/logs should start.

**What did you see instead?**
Sometimes logs/traces doesn't start.

**What version did you use?**
Custom binary - `otelcol version 1.0.0`

**What config did you use?**
```
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
      check_collector_pipeline:
        enabled: true
        interval: "5m"
        exporter_failure_threshold: 5
    memory_ballast:
      size_in_percentage: 40
  receivers:
    myreceiver/metrics: # this line represents the ID of your receiver
      collection_interval: 60s
      sliding_window_offset: 60s
      timeout: 60s

    newrelic/flows:
      collection_interval: 60s
      sliding_window_offset: 60s

    newrelic/flows-2:
      collection_interval: 60s
      sliding_window_offset: 60s

    newrelic/flows-3:
      collection_interval: 60s
      sliding_window_offset: 60s

    newrelic/traces:
      collection_interval: 60s
      sliding_window_offset: 60s

    otlp:
      protocols:
        grpc:
          endpoint: localhost:4317

  processors:
    batch:

    resource:
      attributes:
    
    metricstransform:
      transforms:

  exporters:
    logging:
      verbosity: detailed

  service:
    pipelines:
      metrics:
        receivers:
          - myreceiver/metrics
        processors:
          - batch
          - metricstransform
          - resource
        exporters:
          - logging
      traces:
        receivers:
          - myreceiver/traces
        processors:
          - batch
        exporters:
          - logging
      logs:
        receivers:
          - myreceiver/flows
          - myreceiver/flows-2
          - myreceiver/flows-3
        processors:
          - batch
        exporters:
          - logging
```

**Environment**
Ubuntu 
Compiler(if manually compiled): go version go1.20.5 linux/amd64

**Comment by mx-psi** [comment] 2023-07-25 09:50
@lshmeet Are you able to reproduce this with any receivers available on opentelemetry-collector-contrib? What version of the core libraries are you using? It would be great to have a minimal example where you can reproduce this.

**Comment by mx-psi** [comment] 2024-05-20 15:10
Thanks for clarifying! It seems then like, since we have not seen this issue in any components from contrib, there is no action needed on this issue, right? It also does not seem like there is much we can do to make the error more visible or improve docs

**Comment by mx-psi** [comment] 2024-05-20 20:27
Thanks again!! I am going to close this as wontfix then

**Closed by mx-psi** 2024-05-20 20:27 UTC
Labels: bug, waiting-for-author
