### ISSUE TITLE
[pdata] Inconsistent behavior of `oneof` proto field accessors

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#4775] opened 2022-01-31 21:06 UTC
`NumberDataPoint/Exemplar` accessors to `oneof value` proto field (`IntVal` and `DoubleVal`) return zero value in case of mismatch with underlying proto data type.

`Metric` accessors to `oneof data` proto field (`Gauge`, `Sum` etc) cause a panic in case of mismatch with underlying proto data type.

Should we consider making it consistent and changing the `NumberDataPoint/Exemplar.Value` accessors to panic as well (in a backward compatible manner)? It also saves us a cycle currently spent on the type comparison.

cc @bogdandrutu @codeboten

**Comment by codeboten** [comment] 2022-02-02 17:38
`IntVal`/`DoubleVal` is consistent with the implementation for Attributes, are you suggesting that should be changed as well?

> panic as well (in a backward compatible manner)?

Can you elaborate on how this would work?

**Comment by dmitryax** [comment] 2022-02-03 01:01
> IntVal/DoubleVal is consistent with the implementation for Attributes, are you suggesting that should be changed as well?

Yes, I think we should do the same for `AttributeValue`. Especially because `AttributeValue` getters return complex data types initialized with zero values and detached from the receiver argument. For example let's look at the following code which is currently valid:

```
initialMap := pdata.NewAttributeMap()
initialMap.InsertInt("key", 9)
intValue, _ := initialMap.Get("key")
mapValue := intValue.MapVal()  // I believe this should cause panic instead on returning a new `AttributeMap` detached from `initialMap`
```

And `Metric` `oneof` accessors do cause panics:
```
m := pdata.NewMetric()
m.SetDataType(pdata.MetricDataTypeGauge)
m.Sum() // Panic!
```

We could also return `NewSum()` from `m.Sum()` in case of mismatch to bring it to consistency with `AttributeValue` and `NumberDataPoint/Exemplar`, but I don't think it's a good idea. I think current `Metric` behavior is what we need adapt in other `oneof` field accessors.

> > panic as well (in a backward compatible manner)?

> Can you elaborate on how this would work?

Do you mean backward compatibility? We would need to introduce replacement methods and deprecate current ones. For example `IntVal` -> `IntValue`, `MapVal` -> `MapValue`. Maybe we can keep the later going forward or switch back during the `pdata` -> `pmetric` package restructure.

**Comment by dmitryax** [comment] 2022-02-03 17:50
I might be missing some context justifying the current behavior. @open-telemetry/collector-approvers please let me know

**Comment by bogdandrutu** [comment] 2022-02-03 19:08
```golang
am := pdata.NewAttributeMap()
am.InsertInt("key", 9)
intValue, _ := am.Get("key")
mapValue := intValue.MapVal()  // I believe this should cause panic instead on returning a new `AttributeMap` detached from `am`
mapValue.UpsertString("key", "test") // this will just be ignored correct?
```

I think this is an error prone API/implementation in my opinion.

**Comment by dmitryax** [comment] 2022-02-03 19:15
> this will just be ignored correct?

This will mutate `mapValue` and add `key: test` to it, but `mapValue` is not a part of the original `am` anymore.

> I think this is an error prone API/implementation in my opinion.

I agree

**Comment by bogdandrutu** [comment] 2022-03-13 15:31
@dmitryax so we have some concrete options here:
1. Panic immediately when calling to return a different type, which seem to not be the nicest API. The API you tried to implement.
2. Return a "default/uninitialized" value (like Google's protobuf generated code). This panics when access members that may be nil as default / zero-value:
```golang
am := pdata.NewAttributeMap()
am.InsertInt("key", 9)
intValue, _ := am.Get("key")
mapValue := intValue.MapVal() // returns zero-initialized AttributeMap (== AttributeMap{})
mapValue.UpsertString("key", "test") // Panic here
```
3. Return a "errror" as proposed in a different PR.
4. Return a "bool" as the type conversion API in golang.

My vote is for 2 since indeed is less aggressive than 1. but it also achieves the result of telling the users that they made a mistake. The argument that this will cause a crash is the same as telling someone that writes unchecked type conversion that they should not do that. Returning an error will cause lots of annoying people, and the error will be ignored, because majority of the correct usages are something like (and will be extremely bad to have to check again an error or a bool, even to ignore it):
```golang
	switch a.Type() {
	case AttributeValueTypeEmpty:
		return ""
	case AttributeValueTypeString:
		return a.StringVal()
	case AttributeValueTypeBool:
		return strconv.FormatBool(a.BoolVal())
	case AttributeValueTypeDouble:
		return strconv.FormatFloat(a.DoubleVal(), 'f', -1, 64)
	case AttributeValueTypeInt:
		return strconv.FormatInt(a.IntVal(), 10)
	case AttributeValueTypeMap:
		jsonStr, _ := json.Marshal(a.MapVal().AsRaw())
		return string(jsonStr)
	case AttributeValueTypeBytes:
		return base64.StdEncoding.EncodeToString(a.BytesVal())
	case AttributeValueTypeArray:
		jsonStr, _ := json.Marshal(a.SliceVal().asRaw())
		return string(jsonStr)
	default:
		return fmt.Sprintf("<Unknown OpenTelemetry attribute value type %q>", a.Type())
	}
```

**Comment by Aneurysm9** [comment] 2022-03-14 18:05
My preference would also be for 2.  It is for the most part what we're already doing, a lot safer than 1) for most uses and just as performant.  The other alternative I see as viable is 4), but that has the issue that we cannot exactly replicate the behavior of type conversion as we cannot return either one or two values depending on call context.

It seems that (for `AttributeValue` at least) the difference between 2) and what we do today is that rather than returning uninitialized `AttributeMap` or `AttributeValueSlice` instances, we return values initialized with empty, detached underlying data.  From a safety perspective this may be the better option as it does not present an opportunity to panic, but it can result in unexpected behavior when changes to the returned value are not reflected in the `AttributeValue` it was retrieved from.  

> because majority of the correct usages are something like...

While this may be trivially true by saying that that usage pattern defines "correct usage", it doesn't seem to be the way things are actually done.  There are 31 instances of `switch .*\.Type\(\)` in the contrib codebase while there are 103 instances of `\.StringVal\(\)`.  Double and Int are similarly frequently accessed without such rigor:

```
.StringVal():        103
.BoolVal():           32
.DoubleVal():         69
.IntVal():            78
.MapVal():            36
.BytesVal():           2
.SliceVal():          35
```

**Comment by dmitryax** [comment] 2022-03-14 18:32
The 2) seems a good alternative to me as well. The behavior for primitive types stays the same. The changed behavior for complex types uncovers the problem of misuse much sooner and prevents unexpected consequences that are hard to debug which seems like an improvement to me.

In this case we should do the same for metric type accessors for consistency https://github.com/open-telemetry/opentelemetry-collector/blob/b9a10cdc6e597afe5e4a8619965fbfbc00708cbc/model/internal/pdata/generated_metrics.go#L630-L663
Currently there are no way to create `pdata.Gauge`, `pdata.Sume` or others with `nil` wrapped value. But I think it's ok to have. cc @bogdandrutu

**Comment by bogdandrutu** [comment] 2022-03-15 11:42
> Currently there is no way to create pdata.Gauge, pdata.Sume or others with nil wrapped value. But I think it's ok to have.

just return `pdata.Gauge{}` (zero-initialized struct which is invalid to use).

```golang
 func (ms Metric) Sum() Sum {
	if x, ok := (*ms.orig).Data.(*otlpmetrics.Metric_Sum); ok {
 		return newSum(x.Sum)
	}
	return Sum{}
 } 
```

@dmitryax I think we have a winer, so let's do that.

**Comment by dmitryax** [comment] 2022-03-16 06:37
@bogdandrutu @Aneurysm9 

Given that the change we agreed on (2) affects only wrong usage of `AttributeValue.MapVal()` and `AttributeValue.SliceVal()` which should not exist in practice, can we agree to make an exception to the breaking changes policy and keep existing `AttributeValue....Val()` functions without replacing them with the new `AttributeValue....Value()` functions? I checked contrib and didn't find any wrong usages of the collection accessors, but will double check it again before the upgrade.

It's different for `Metric.Sum()`, `Metric.Gauge()` change. The behavior of the wrong usage of will be changed, but instead of raising panic right away, they'll be returning an invalid structure. I don't think this can be considered a breaking change, so I believe it's safe to change them in place as well.

**Comment by bogdandrutu** [comment] 2022-03-16 07:37
> It's different for Metric.Sum(), Metric.Gauge() and other metric type accessors. The behavior of their misuse will be changed, but instead of raising panic right away, they'll be returning an invalid structure. I don't think this can be considered a breaking change, so I believe it's safe to change them in place as well.

I think changing directly there is fine, since we relax the API.

> Given that the change we agreed on (2) affects only wrong usage of AttributeValue.MapVal() and AttributeValue.SliceVal() which should not exist in practice, can we agree to make an exception to the breaking changes policy and keep existing AttributeValue*.Val() functions without replacing them with the new AttributeValue*.Value() functions? I checked contrib and didn't find any misuse of the collection accessors, but will double check it again before the upgrade.

I am ok with this "exception" change.

**Comment by Aneurysm9** [comment] 2022-03-16 15:50
I am okay with making these changes directly.  Thanks for clearly laying out the case for policy exception here.

**Comment by dmitryax** [comment] 2022-03-18 01:04
@Aneurysm9 @bogdandrutu thanks for your feedback.

I submitted two PRs for the (2) approach:
- https://github.com/open-telemetry/opentelemetry-collector/pull/5035 
- https://github.com/open-telemetry/opentelemetry-collector/pull/5034

**Comment by bogdandrutu** [comment] 2022-03-22 15:05
Closing this, since I believe we are done. @dmitryax feel free to reopen if that is not the case.

**Closed by bogdandrutu** 2022-03-22 15:05 UTC
