### ISSUE TITLE
Bug report for failed CircleCI build (job: loadtest)

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#1565] opened 2020-08-17 14:35 UTC
Auto-generated report for `loadtest` job build.

Link to failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/24196

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

**Comment by tigrannajaryan** [comment] 2020-08-19 17:49
Appears to be a temporarily glitch in CircleCI, they are passing now. Closing for now, will reopen if happens again to see what's the root cause.

**Closed by tigrannajaryan** 2020-08-19 17:49 UTC
