### ISSUE TITLE
Flaky test: TestQueuedRetry_RequeuingEnabled

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#6624] opened 2022-11-25 00:17 UTC
Seen this failure a couple of times: 

https://github.com/open-telemetry/opentelemetry-collector/actions/runs/3524647585/jobs/5910347724
https://github.com/open-telemetry/opentelemetry-collector/actions/runs/3521003167/jobs/5951483003

```
=== RUN TestQueuedRetry_RequeuingEnabled
panic: sync: negative WaitGroup counter
goroutine 178 [running]:
sync.(*WaitGroup).Add(0xc000046730, 0xffffffffffffffff)
/opt/hostedtoolcache/go/1.18.7/x64/src/sync/waitgroup.go:80 +0x1f8
sync.(*WaitGroup).Done(...)
/opt/hostedtoolcache/go/1.18.7/x64/src/sync/waitgroup.go:105
go.opentelemetry.io/collector/exporter/exporterhelper.(*observabilityConsumerSender).send(0xc000094e40, {0x1296340, 0xc00015bd80})
/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/queued_retry_test.go:683 +0x108
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x1296340, 0xc00015bd80})
/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/queued_retry.go:205 +0x65
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/bounded_memory_queue.go:61 +0x144
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/bounded_memory_queue.go:56 +0x68

FAIL go.opentelemetry.io/collector/exporter/exporterhelper 0.421s
```

**Comment by Saggi432** [comment] 2023-01-23 18:15
@codeboten I am new to Opentelemetry .. but willing to work on this issue.. pls lmk.. if I can.

**Comment by codeboten** [comment] 2023-01-23 22:15
Thanks @Saggi432! I've assigned it to you

**Comment by Abhishek-569** [comment] 2023-03-08 11:09
I want to work on this issue. Can anyone explain more about this? Thanks.

**Comment by Saggi432** [comment] 2023-03-09 01:05
I apologize I haven't been able to spend time on it.. @Abhishek-569 feel free to take It from me..

**Comment by gord02** [comment] 2023-09-28 00:42
Hello @Abhishek-569! I am new to the OpenTelemetry community and want to contribute. Is a fix for this issue still required? If so, I'd be happy to try and find something with any guidance you might be able to provide.

**Comment by atoulme** [comment] 2023-09-28 01:17
Looks like it's still occurring:
https://github.com/open-telemetry/opentelemetry-collector/actions/runs/6255311581/job/16984423659
https://github.com/open-telemetry/opentelemetry-collector/actions/runs/6238147660/job/16933380928

**Comment by berkeli** [comment] 2023-11-23 20:57
I will take a look at this, I was able to reproduce it consistenly few times with
` go test -race -run TestQueuedRetry_RequeuingEnabled -count 1000`

The command must be run in `exporter/exporterhelper` for quicker feedback loop

**Closed** 2023-11-24 03:42 UTC
Labels: bug, help wanted, good first issue
