### ISSUE TITLE
compilation failed  with message call to non-variadic sdkmetric.WithReader

### ISSUE THREAD

**Issue by k-p-ani** [open-telemetry/opentelemetry-collector#6721] opened 2022-12-09 14:24 UTC
**Describe the bug**
while building our telemetric app getting below compilation error
github.com/open-telemetry/opentelemetry-collector-contrib/internal/sharedcomponent
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter
go.opentelemetry.io/collector/service
../../../pkg/mod/go.opentelemetry.io/collector@v0.67.0/service/**telemetry.go:256:3: cannot use ... in call to non-variadic sdkmetric.WithReader**

**Steps to reproduce**
try to build an pipeline app that read host metrics using  host metrics receiver from
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.66.0/receiver/hostmetricsreceiver
and exporter from
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.66.0/exporter/fileexporter

**What did you expect to see?**
code should have compiled

**What did you see instead?**
compilation error as mentioned at the top

**What version did you use?**
Version:  `v0.67.0`

**What config did you use?**
N/A

**Environment**
OS: "macOS 13.0.1"
Compiler(if manually compiled): ("go 1.19.2")

**Additional context**

**Comment by bogdandrutu** [comment] 2022-12-09 16:22
We are in the middle of the release v0.67.0, I think this will not be a problem after contrib is also released.

**Comment by k-p-ani** [comment] 2022-12-10 06:20
so for now which version should I consider, to avoid this issue ?

**Comment by bogdandrutu** [comment] 2022-12-12 18:30
You are using a newer version of the otel-go library. You need to downgrade that to the previous version, the problem is not on our side.

**Comment by bogdandrutu** [comment] 2022-12-12 19:16
So use the v0.67.0, but  use `go.opentelemetry.io/otel/metric 0.33.0` and `go.opentelemetry.io/otel/sdk/metric 0.33.0`

**Comment by bogdandrutu** [comment] 2022-12-13 19:34
Closing this, since the problem is not on our side, but on the fact that otel-go broke between v0.33 and v0.34

**Closed** 2022-12-13 19:34 UTC
Labels: bug
