### ISSUE TITLE
Issue using environment variable for pipelines

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector#10799] opened 2024-08-04 14:14 UTC
**Describe the bug**
Environment variables used for pipelines are not processed correctly in 0.106.1, while they worked in 0.105.0. I have tried to put the value in double quotes and disable the confmap.strictlyTypedInput feature gate without success.

I a receiving an error instead.

When using confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: retrieved value does not have unambiguous string representation: [filelog windowseventlog/application]

When using -confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: expected convertable to string value type, got ["filelog" "windowseventlog/application"]([]interface {})

**What version did you use?**
0.106.1

**What config did you use?**
```
    logs:
      receivers: ${env:OTEL_LOGS_RECEIVER}
      processors: [memory_limiter,resourcedetection/system,resource/environment,transform,filter,batch]
      exporters: ${env:OTEL_LOGS_EXPORTER}
```

With [filelog,windowseventlog/application]  as the environment value for OTEL_LOGS_RECEIVER as an example.

**Environment**
Windows 2022 Server

**Comment by kago-dk** [comment] 2024-08-04 14:21
Tagging @mx-psi @TylerHelmuth

**Comment by mx-psi** [comment] 2024-08-05 09:27
@kago-dk Could you share the exact value of your `OTEL_LOGS_RECEIVER` and `OTEL_LOGS_EXPORTER` environment variables?

**Comment by mx-psi** [comment] 2024-08-05 09:58
Failed attempt at reproducing this (edited for clarity):

```
❯ cd $(mktemp -d)

❯ curl -L -o contrib-0.106.1.tar.gz <URL for contrib>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 28.6M  100 28.6M    0     0  11.5M      0  0:00:02  0:00:02 --:--:-- 24.0M

❯ tar pfx contrib-0.106.1.tar.gz 

❯ cat config.yaml
receivers:
  otlp/1:
    protocols:
      grpc:
  hostmetrics:
    scrapers:
      load:

exporters:
  debug:

service:
  pipelines:
    logs:
      receivers: ${env:OTEL_LOGS_RECEIVER}
      exporters: [debug]

❯ OTEL_LOGS_RECEIVER=[otlp/1,hostmetrics] ./otelcol --config config.yaml 

<runs as usual>
```

**Comment by kago-dk** [comment] 2024-08-05 14:30
The content respectively is [filelog,windowseventlog/application] and [splunk_hec,otlphttp/loki/abcd] for OTEL_LOGS_RECEIVER and OTEL_LOGS_EXPORTER. The values are set at Windows Environment Variables and not used elsewhere in the Otel Configuration.

I load the pipeline section into otel-config.yaml.
```
service:
  pipelines: ${file:${env:ProgramFiles}/otelcol/pipelines/pipelines.yaml}
```

It sounds like the issue is resolved as part of a different ticket?

**Comment by mx-psi** [comment] 2024-08-05 15:06
Yes, I think this is a duplicate of #10787. I am going to add a test case for this to verify it

**Closed** 2024-08-07 13:26 UTC
Labels: bug, release:blocker, area:confmap
