### ISSUE TITLE
OTLP Log Exporter omits severityText log field 

### ISSUE THREAD

**Issue by mmorev** [open-telemetry/opentelemetry-collector#7535] opened 2023-04-13 07:30 UTC
**Describe the bug**
I collect logs from a Java application with opentelemetry-javaagent installed, using otlp.

Logs contain `severityNumber` field, but not `severityText`. I have added transformProcessor to parse severityNumber to severityText, and configured log exporters to otlp and logging so I can compare modified log event with one stored in storage backend (elasticsearch btw).

Then I can see log events in stdout, and they contain parsed severityText value, so it should appear in the event in storage backend, but they don't.

What I'm doing wrong?

**Steps to reproduce**
- receive a log event without `severityText` field using **otlp receiver**
- set this field using **transformprocessor**
- export a log event to both **otlp exporter** and **logging exporter**

**Log event in stdout:**
```
2023-04-13T07:19:39.635Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
2023-04-13T07:19:39.635Z	info	ResourceLog #0
Resource SchemaURL: https://opentelemetry.io/schemas/1.18.0
Resource attributes:
     -> container.id: Str(f15f98750cc1263a50943f65ff68e309860a3ca3b70ccb2fc6150f8209f9c3a2)
     -> k8s.container.name: Str(my-application)
     -> k8s.deployment.name: Str(my-application)
     -> k8s.namespace.name: Str(my-app-namespace)
     -> k8s.node.name: Str(k8s-worker-hostname)
     -> k8s.pod.name: Str(my-application-64b55884c6-s6vjp)
     -> k8s.replicaset.name: Str(my-application-64b55884c6)
     -> service.name: Str(my-application)
     -> telemetry.sdk.language: Str(java)
     -> telemetry.sdk.name: Str(opentelemetry)
     -> telemetry.sdk.version: Str(1.23.1)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope akka.http.impl.util.StreamUtils$DelayCancellationStage$$anon$11 
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-04-13 07:19:39.336 +0000 UTC
SeverityText: Debug
SeverityNumber: Debug(5)
Body: Str(Delaying cancellation for 1 minute)
Trace ID: 5c222a505c4ddc6d0fd4b7f35ac31663
Span ID: 7cc5a2bfad79b290
Flags: 1
	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```

**Same event in opensearch index:**
```json:
{
  "_index": "otel-logs",
  "_id": "Lpd8eYcB6bo34PIMAZ0v",
  "_version": 1,
  "_score": 0,
  "_source": {
    "traceId": "5c222a505c4ddc6d0fd4b7f35ac31663",
    "spanId": "7cc5a2bfad79b290",
    "flags": 1,
    "time": "2023-04-13T07:19:39.336Z",
    "severityNumber": 5,
    "droppedAttributesCount": 0,
    "serviceName": "my-application",
    "body": "Delaying cancellation for 1 minute",
    "observedTime": "1970-01-01T00:00:00Z",
    "schemaUrl": "https://opentelemetry.io/schemas/1.18.0",
    "instrumentationScope.name": "akka.http.impl.util.StreamUtils$DelayCancellationStage$$anon$11",
    "resource.attributes.k8s@namespace@name": "my-app-namespace",
    "resource.attributes.k8s@node@name": "k8s-worker-hostname",
    "resource.attributes.k8s@deployment@name": "my-application",
    "resource.attributes.telemetry@sdk@name": "opentelemetry",
    "resource.attributes.k8s@container@name": "my-application",
    "resource.attributes.telemetry@sdk@language": "java",
    "resource.attributes.container@id": "f15f98750cc1263a50943f65ff68e309860a3ca3b70ccb2fc6150f8209f9c3a2",
    "resource.attributes.telemetry@sdk@version": "1.23.1",
    "resource.attributes.service@name": "my-application",
    "resource.attributes.k8s@replicaset@name": "my-application-64b55884c6",
    "resource.attributes.k8s@pod@name": "my-application-64b55884c6-s6vjp"
  },
  "fields": {
    "time": [
      "2023-04-13T07:19:39.336Z"
    ],
    "observedTime": [
      "1970-01-01T00:00:00.000Z"
    ]
  },
  "highlight": {
    "traceId": [
      "@opensearch-dashboards-highlighted-field@5c222a505c4ddc6d0fd4b7f35ac31663@/opensearch-dashboards-highlighted-field@"
    ]
  }
}
```

**What did you expect to see?**
a log event containing `severityText` field both in stdout and storage backend

**What did you see instead?**
a log event in storage backend doesn't contain `severityText` field, while stdout does

**What version did you use?**
Version: opentelemetry-collector-contrib 0.75.0

**What config did you use?**
otel-collector.yaml:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${MY_POD_IP}:4317
exporters:
  logging:
    verbosity: detailed
  otlp/logs:
    endpoint: data-prepper.opensearch.svc.cluster:21892
processors:
  transform/severity_parse:
    log_statements:
      - context: log
        statements:
        - set(severity_text, "Trace")  where severity_number > 0  and severity_number <= 4
        - set(severity_text, "Debug")  where severity_number > 4  and severity_number <= 8
        - set(severity_text, "Info")   where severity_number > 8  and severity_number <= 12
        - set(severity_text, "Warn")   where severity_number > 12 and severity_number <= 16
        - set(severity_text, "Error")  where severity_number > 16 and severity_number <= 20
        - set(severity_text, "Fatal")  where severity_number > 20 and severity_number <= 24
service:
  pipelines:
    logs:
      exporters:
      - otlp/logs
      - logging
      processors:
      - transform/severity_parse
      receivers:
      - otlp
  telemetry:
    logs:
      level: debug
```

**Environment**
Kubernetes 1.21

**Comment by astencel-sumo** [comment] 2023-05-30 12:04
This is not a bug in the collector. In my testing (v0.77.0), the OTLP exporter correctly outputs both SeverityNumber and SeverityText. I'd suggest to report this issue in the OpenSearch product (perhaps the [Data Prepper](https://github.com/opensearch-project/data-prepper/)?).

To verify that the OTLP exporter correctly outputs the severity text, I've set up two instances of Otelcol:
- Otelcol 1, that produces/receives logs with the severity text and number and outputs these logs via OTLP exporter to...
- Otelcol 2, that accepts logs via OTLP receiver and logs them with the Logging exporter.

You should be able to see the SeverityText correctly displayed by the Logging exporter of Otelcol 2, which proves that the OTLP exporter from Otelcol 1 correctly exporter the data.

`otelcol1.yaml`:

```yaml
exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: http://localhost:4315
    tls:
      insecure: true

receivers:
  otlpjsonfile:
    include:
    - ./logs.json
    start_at: beginning

service:
  pipelines:
    logs:
      exporters:
      - logging
      - otlp
      receivers:
      - otlpjsonfile

  telemetry:
    metrics:
      address: :8881
```

`otelcol2.yaml`:

```yaml
exporters:
  logging:
    verbosity: detailed

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4315

service:
  pipelines:
    logs:
      exporters:
      - logging
      receivers:
      - otlp

  telemetry:
    metrics:
      address: localhost:8882
```

`logs.json`:

```json
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"observedTimeUnixNano":"1685446640739329194","body":{"stringValue":"- filelog"},"severityText":"medium","severityNumber":9,"attributes":[{"key":"log.file.name","value":{"stringValue":"otc-filelog-receiver-file-exporter.yaml"}}],"traceId":"","spanId":""}]}]}]}
```

Put all files in one directory and run both otelcol instances:

```console
$ otelcol-contrib --config otelcol2.yaml
```

```console
$ otelcol-contrib --config otelcol1.yaml
```

You should see the following in otelcol 2 output:

```console
2023-05-30T13:59:00.564+0200    info    service/telemetry.go:113        Setting up own telemetry...
2023-05-30T13:59:00.564+0200    info    service/telemetry.go:136        Serving Prometheus metrics      {"address": "localhost:8882", "level": "Basic"}
2023-05-30T13:59:00.564+0200    info    exporter@v0.77.0/exporter.go:286        Development component. May change in the future.        {"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-05-30T13:59:00.585+0200    info    service/service.go:141  Starting otelcol-contrib...     {"Version": "0.77.0", "NumCPU": 16}
2023-05-30T13:59:00.585+0200    info    extensions/extensions.go:41     Starting extensions...
2023-05-30T13:59:00.586+0200    info    otlpreceiver@v0.77.0/otlp.go:94 Starting GRPC server    {"kind": "receiver", "name": "otlp", "data_type": "logs", "endpoint": "localhost:4315"}
2023-05-30T13:59:00.586+0200    info    service/service.go:158  Everything is ready. Begin running and processing data.
2023-05-30T13:59:11.741+0200    info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 1, "log records": 1}
2023-05-30T13:59:11.741+0200    info    ResourceLog #0
Resource SchemaURL: 
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2023-05-30 11:37:20.739329194 +0000 UTC
Timestamp: 1970-01-01 00:00:00 +0000 UTC
SeverityText: medium
SeverityNumber: (9)
Body: Str(- filelog)
Attributes:
     -> log.file.name: Str(otc-filelog-receiver-file-exporter.yaml)
Trace ID: 
Span ID: 
Flags: 0
        {"kind": "exporter", "data_type": "logs", "name": "logging"}
```

**Comment by KarstenSchnitter** [comment] 2023-08-29 05:39
Indeed, this is an issue in DataPrepper. I created https://github.com/opensearch-project/data-prepper/issues/3280 for this.

**Comment by astencel-sumo** [comment] 2023-09-11 10:20
Thanks a lot @KarstenSchnitter for getting back with this information. Closing this issue then.

**Closed by astencel-sumo** 2023-09-11 10:20 UTC
Labels: bug, priority:p2, exporter/logging
