### ISSUE TITLE
Bug report for failed CircleCI build (job: loadtest)

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#2491] opened 2021-02-14 14:59 UTC
Auto-generated report for `loadtest` job build.

Link to failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/63345

#### Test Failures
-  TestTraceNoBackend10kSPS
-  TestTraceNoBackend10kSPS/MemoryLimit

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

**Comment by jpkrohling** [comment] 2021-06-03 07:11
Duplicate of #2911

**Closed by jpkrohling** 2021-06-03 07:11 UTC
