### ISSUE TITLE
Lazy Load Factories to Improve Memory Usage and Speed Up Startup

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector#5259] opened 2022-04-26 01:12 UTC
**Is your feature request related to a problem? Please describe.**
Currently at start up the collector must load all possible factories into memory via the [Factories](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/factories.go#L25-L37) struct which is embedded in the [CollectorSettings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/settings.go#L47-L69). If there is a large component set in the collector the majority of the factories may not be used.  Depending on how a factory is structured it has the potential to load a large amount of code with it into memory.

Also, since factories exist on the `CollectorSettings`, which exists for the life of the collector, the references to those factories are always valid and they are never garbage collected. This means whatever memory factories consume just by existing is be held through the lifetime of the collector.

**Describe the solution you'd like**
I think a solution would be to lazy load components as we try to get them from the from the [service](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/service.go#L147-L159).  

My proposal to achieve this would be to call a component's `NewFactory()` on a call to `GetFactory` only if a factory for that component doesn't already exist. I think the `Factories` struct would need to be changed in order to contain existing factories and some struct to handle generating new factories.

Something along the lines of this:

```go
type FactoryGenerators struct {
        ReceiverGenerators map[config.Type]func() component.ReceiverFactory

        ProcessorGenerators map[config.Type]func() ProcessorFactory

        ExporterGenerators map[config.Type]func() ExporterFactory

        ExtensionGenerators map[config.Type]func() ExtensionFactory
}

type Factories struct {
	// Receivers maps receiver type names in the config to the respective factory.
	Receivers map[config.Type]ReceiverFactory

	// Processors maps processor type names in the config to the respective factory.
	Processors map[config.Type]ProcessorFactory

	// Exporters maps exporter type names in the config to the respective factory.
	Exporters map[config.Type]ExporterFactory

	// Extensions maps extension type names in the config to the respective factory.
	Extensions map[config.Type]ExtensionFactory
 
        // Generators provides a factory generator function
        Generators *FactoryGenerators
}

func (f *Factories) GetFactory(kind component.Kind, componentType config.Type) component.Factory {
        switch kind {
	case component.KindReceiver:
                 componentFact, ok := f.Receivers[componentType]
                 if !ok {
                     factGen, ok := f.Generators[componentType]
                     if !ok {
                         return nil
                     }

                     componentFact = factGen()
                     f.Receivers[componentType] = componentFact
                 }
		return componentFact
	case component.KindProcessor:
               // Same as Receiver Logic
	case component.KindExporter:
               // Same as Receiver Logic
	case component.KindExtension:
               // Same as Receiver Logic
	}
	return nil
}
```

A further optimization could be to only load the factory when needed then allow it to be garbage collected after it is no longer needed but that is likely a more complex solution and not needed in this initial fix.

**Comment by bogdandrutu** [comment] 2022-04-27 19:53
@cpheps do you have any numbers about this? This to me seem like an unnecessary complication, since I expect the factories to have very minimum amount of memory required.

**Comment by cpheps** [comment] 2022-04-27 20:03
@bogdandrutu not yet. I am ok with closing this proposal though. It was originally meant to help solve the PR that was linked, now removed, but I misunderstood the core problem there.

I left it open to see if there was a general interest. I can work on getting numbers next week just to do due diligence on this but if there's not a strong interest from the community I don't feel I have to push for this.

**Comment by bogdandrutu** [comment] 2022-04-27 20:13
@cpheps unless we prove this is a problem, we should not try to complicate things. On the same note it should be a best practice for "Factories" to not keep alive large amount of resources. Maybe we can document that.

I miss the "linked" PR, can you point me to it?

**Comment by cpheps** [comment] 2022-04-27 20:28
Here is the PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9224. 

I agree on not complicating things. We can close this for now and I can reopen if my tests show a significant difference in memory usage. This might be something worth revisiting as we add more components but likely an over optimization with the current state.

I think a best practice is good but it might be hard to enforce or quantify by reviewers.

**Comment by bogdandrutu** [comment] 2022-04-28 13:42
@cpheps I don't have the same feeling as you that this will ever be a problem.

As you probably realized in that PR, the memory footprint increases way more because of the binary size caused by dependencies that we add with every component

**Comment by bogdandrutu** [comment] 2022-04-28 13:43
Per the discussion conclusion I am closing this, waiting for numbers to prove me wrong 😊

**Closed by bogdandrutu** 2022-04-28 13:43 UTC
