### ISSUE TITLE
Prometheus receiver: Move job and instance labels into resource attributes

### ISSUE THREAD

**Issue by scheler** [open-telemetry/opentelemetry-collector#2499] opened 2021-02-16 18:51 UTC
**Is your feature request related to a problem? Please describe.**
Prometheus adds the labels _job_ and _instance_ to identify the target scraped - this maps to the Resource in opentelemetry against which the metrics are associated with. Looks like the Resource is currently empty, we could populate these two labels as attributes under Resource.

**Describe the solution you'd like**
Move (or copy) the two labels _job_ and _instance_ as attributes under Resource.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by odeke-em** [comment] 2021-04-19 00:55
@bjrara resolved this in PR https://github.com/open-telemetry/opentelemetry-collector/pull/2897, but didn't use `Fixes #2499` in the commit message so it didn't auto-close this issue. Please help close this issue @alolita @tigrannajaryan @rakyll.

**Comment by rakyll** [comment] 2021-04-20 03:17
Duplicate of https://github.com/open-telemetry/wg-prometheus/issues/37. 

https://github.com/open-telemetry/opentelemetry-collector/pull/2897 is not solving this issue.

**Closed** 2021-04-22 22:20 UTC
Labels: area:prometheus, priority:p2
