### ISSUE TITLE
Support loading configuration files from a directory

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-collector#10221] opened 2024-05-24 19:46 UTC
**Is your feature request related to a problem? Please describe.**
Currently we can specify multiple configurations by repeatedly applying the `--config` flag. In dynamic environments, it may not be known ahead of time how many configs need to be loaded.

**Describe the solution you'd like**
Introduce a new flag `--config-dir` that can be specified at runtime. The Collector will look in this directory for configuration files, validate them, and load them as if they were passed in by repeated application of the `--config` flag. If a file is found with invalid config, the collector would skip loading it and log a warning.

**Describe alternatives you've considered**
Statically defining all possible configurations. But this is quite clunky, and requires code changes and releases if new configuration modules are introduced.

**Comment by TylerHelmuth** [comment] 2024-05-29 02:47
I believe this is a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/10221.  Please ping me to reopen if you feel differently.

**Closed by TylerHelmuth** 2024-05-29 02:47 UTC

**Comment by sinkingpoint** [comment] 2024-05-29 04:01
#10221 seems to be this issue @TylerHelmuth . I think you meant #9596 ?

**Comment by TylerHelmuth** [comment] 2024-05-29 05:08
Yes thank you
