### ISSUE TITLE
Prometheus Job and Instance labels

### ISSUE THREAD

**Issue by liamawhite** [open-telemetry/opentelemetry-collector#575] opened 2020-02-27 01:51 UTC
When using the Prometheus receiver and exporter I no longer get the `job` or `instance` labels that are default in Prometheus. Is this expected behaviour?

When Prometheus scrapes them I lose these fields even with `honor_labels: true`. I have manually checked the metrics and they are missing these labels so it's not an issue with Prometheus. Is there a way to manually add them back in with some `relabel_configs` magic? I have tried but it seems to get ignored whenever I use the `job` or `instance` labels.

I eventually want two exporters here one of which can be scraped locally by Prometheus and the other will forward onto another collecter. Our default use case is without Prometheus so scraping Prometheus with the collector isn't an option. 

Version: v0.2.3

```
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [prometheus]
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9090"  
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.scrapeInterval }}
          scrape_configs:
          - job_name: 'pilot'
            kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - {{ .Release.Namespace }}
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              action: keep
              regex: istio-pilot;http-monitoring
```

```
- job_name: 'oc-agent'
      scrape_interval: 5s
      honor_labels: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: otel-collector;prometheus
```

**Comment by arpitjindal97** [comment] 2020-09-13 20:05
It is so crucial bug and still open from more than 6 months

**Comment by hairyhenderson** [comment] 2020-10-07 18:15
I can confirm this is still the current behaviour. I tried setting the `job` label through a relabel_config, but started getting an error when they didn't match.

The relabel_config I'm using is:

```yaml
                  - source_labels: [__meta_kubernetes_pod_label_k8s_app]
                    target_label: job
```

And I'm seeing this error:

```
{"level":"warn","ts":1602094121.4748123,"caller":"scrape/scrape.go:1058","msg":"Appending scrape report failed","component_kind":"receiver","component_type":"prometheus","component_name":"prometheus","scrape_pool":"etcd-pods","target":"https://10.240.53.137:4001/metrics","err":"unable to find a target group with job=etcd-server"}
```

When I set the `job_name` to be the same as what would get relabeled, the error goes away, but I still see neither `job` nor `instance`.

In my case, I'll be using Prometheus to scrape the otelcol instance, so I'll just use labels _other_ than `job` and `instance` to set them appropriately and then have another relabel_config in Prometheus to set them to what they should be.

I'd like to help fix this, though I'm not sure where to start.

**Comment by pingleig** [comment] 2021-03-12 19:56
The error comes from https://github.com/open-telemetry/opentelemetry-collector/blob/b13bc9d94b4ce597c450310804e0d7ffe3cabb04/receiver/prometheusreceiver/internal/metadata.go#L42-L42 

The problem is the `TargetsAll` in prometheus scrape manager get its keys from the static prometheus scrape config. It has no way to know the job label within each scraped target, which can be set in the following ways

- exported metrics can contain job label https://prometheus.io/docs/concepts/jobs_instances/
- service discovery can set job label directly
- relabel config based on meta label from service discovery
- in static scrape config as `job_name` (lowest priority, only used when there is no job label from other places)

However, in otel's prometheus receiver, it can't distinguish the source of job label https://github.com/open-telemetry/opentelemetry-collector/blob/b13bc9d94b4ce597c450310804e0d7ffe3cabb04/receiver/prometheusreceiver/internal/transaction.go#L123-L123


One way to workaround as a user is instead of using `job` label,  rename it to `job1` and you will pass the prometheus receiver. Then down the pipeline use processors like [Metrics Transform Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) to rename is back to `job` so exporters can the right job label ... (I haven't tested it hough ...

Another way to workaround this is  having the receiver figure out a way to have a `scrape_job` label that won't get override and always match the `job_name` in `scrape_configs`. Inside the internal package, check this hidden label and remove it after usage so it won't passed down the pipeline.

**Comment by bjrara** [comment] 2021-04-07 02:39
Prometheus receiver needs `job` and `instance` label to find the corresponding scraping target and the metric metadata from the cache. The metadata is used to build otel Metrics which would be passed through the pipeline.

### How to get the target?
Currently, there's no good way to get the correct target when receiving metrics from Prometheus. **The [Appender interface](https://github.com/prometheus/prometheus/blob/431ea75a11ca165dad9dd5d629b3cf975f4c186b/storage/interface.go#L159) doesn't support target information propagation.**

Yet the target is known to the appender when it is first initiated. [Ref](https://github.com/prometheus/prometheus/blob/431ea75a11ca165dad9dd5d629b3cf975f4c186b/scrape/scrape.go#L276)
```
return newScrapeLoop(
	...
	func(l labels.Labels) labels.Labels { return mutateReportSampleLabels(l, opts.target) },
	func(ctx context.Context) storage.Appender { return appender(app.Appender(ctx), opts.limit) },
```
It's possible to add target metadata to Appender creation process.

Also there's another open PR (https://github.com/prometheus/prometheus/pull/7771) from Prometheus repo that suggests to pass target metadata into `Appender` in `Add`. However, this PR has been stable for 3 months, and I don't know if there would be any follow up actions.
```
type Appender interface {
	Add(l labels.Labels, m Metadata, t int64, v float64) (uint64, error)
}
```
### Re/label restriction in Prometheus receiver
Today, prometheus receiver could only use `job` and `instance` to find the scraping target which puts an extra undocumented restriction on label and relabel.
https://github.com/open-telemetry/opentelemetry-collector/blob/b13bc9d94b4ce597c450310804e0d7ffe3cabb04/receiver/prometheusreceiver/internal/metadata.go#L39-L48

The `unable to find a target group` error can be triggered by
1) Labeling original metrics with `job` or `instance`;
2) Relabeling `job` or `instance` in the scrape config to a different value.

Although Prometheus receiver should be able to identify `job` and `instance` in _case 1_ when `hornor_label` is set to false where label conflicts would be resolved with [exported_ prefix](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config), it's hard to distinguish whether it is auto generated by Prometheus or added by users. 

Before the issue is fixed, I would suggest people avoid changing these two labels.

**Comment by rakyll** [comment] 2021-04-07 22:50
cc @odeke-em

**Comment by rakyll** [comment] 2021-04-07 22:52
We will automatically add job and instance labels, this is a known bug. Related to https://github.com/open-telemetry/wg-prometheus/issues/7.

**Comment by bjrara** [comment] 2021-04-08 02:05
> We will automatically add job and instance labels, this is a known bug. Related to [open-telemetry/wg-prometheus#7](https://github.com/open-telemetry/wg-prometheus/issues/7).

I've submitted a fix for auto labeling. https://github.com/open-telemetry/opentelemetry-collector/pull/2897

**Comment by rakyll** [comment] 2021-04-20 03:16
Duplicate of https://github.com/open-telemetry/wg-prometheus/issues/37.

**Closed** 2021-04-22 22:20 UTC
Labels: help wanted
