### ISSUE TITLE
User experience: starting the collector without config file yields a cryptic message

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#5648] opened 2022-07-07 19:12 UTC
When running the collector without specifying a config file, the error message that is returned doesn't immediately make it clear to users what the problem is:

```
$ ./bin/otelcorecol_linux_amd64 
Error: invalid map resolver config: no URIs
2022/07/07 16:08:11 collector server run finished with error: invalid map resolver config: no URIs
```

I would prefer to have a validation somewhere before this error, stating that a configuration file is required to run the collector. I believe we even had this a few releases ago.

**Comment by josephwoodward** [comment] 2022-07-07 19:19
Feel free to assign this to me.

**Comment by svrnm** [comment] 2022-07-07 20:23
I am wondering if instead of throwing an error the collector could just start with a minimal configuration (otlp receivers, debug logging exporters for all signals)? Or would this be unexpected behavior / lead to more confusion ?

**Comment by mx-psi** [comment] 2022-07-08 08:12
> I am wondering if instead of throwing an error the collector could just start with a minimal configuration (otlp receivers, debug logging exporters for all signals)? Or would this be unexpected behavior / lead to more confusion ?

We have that on the Helm chart, and it seems to have mixed feedback: open-telemetry/opentelemetry-helm-charts#90. We also have it on the Docker images, for which I have heard anecdotal negative feedback when open-telemetry/opentelemetry-collector-releases/issues/59 happened (since the Collector did not fail to start, just started with a different configuration). 

IMO it's hard to agree on what this minimal configuration should be: different people have different ideas and use cases in mind, and the official binaries should probably be neutral in this regard and just provide high-quality examples

**Comment by josephwoodward** [comment] 2022-08-12 23:31
Started looking into this and can confirm it used to error with the following message:

```
$ ./otelcol-dev
Error: failed to get config: invalid configuration: no enabled receivers specified in config
2022/08/13 00:30:23 collector server run finished with error: failed to get config: invalid configuration: no enabled receivers specified in config
```

**Comment by TylerHelmuth** [comment] 2022-08-23 17:38
@jpkrohling when you said "configuration file is required to run the collector" do you mean an actual configuration file, or do you mean configuration provided via [any valid source](https://github.com/open-telemetry/opentelemetry-collector/tree/main/service#how-to-provide-configuration)?

**Comment by TylerHelmuth** [comment] 2022-08-23 17:55
@josephwoodward I think we can check for the presence of a `--config` flag [here](https://github.com/open-telemetry/opentelemetry-collector/blob/62d41a8ac401cdcb3b0fd7b067d2eecc64f0cc8b/service/command.go#L38), and if there are not any we can error accordingly.  Let me know if you are still working on it.  If not, I can pick this up.

**Comment by jpkrohling** [comment] 2022-08-23 20:04
Sorry, I meant a configuration provided from any valid source.

**Closed** 2022-08-26 21:16 UTC
Labels: bug, good first issue, easy
