### ISSUE TITLE
add the limit of size(not count of log but bytes) for single request

### ISSUE THREAD

**Issue by yutingcaicyt** [open-telemetry/opentelemetry-collector#6569] opened 2022-11-17 04:17 UTC
## Important (read before submitting)
We are currently preparing for the upcoming 1.0 GA release. Feature requests that are not aligned with
the current roadmap https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/roadmap.md
and are not aimed at stabilizing and preparing the Collector for the release will not be prioritized.

_Delete this paragraph before submitting._

**Is your feature request related to a problem? Please describe.**
In our situation, we have a lot of different servicies to collect logs which means the log size(bytes) may differs a lot(1k to 1M). For this, the log count limit for single request is not enough, because the size of a single http request may reach 1GB maximumly(if the log count limit is 1000). So if there is a config that can limit the bytes size of a request would be better.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by dmitryax** [comment] 2023-12-09 18:16
@yutingcaicyt can this be closed as a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/8272?

**Closed** 2023-12-25 02:13 UTC
