### ISSUE TITLE
Regression - gRPC option 'insecure: true' has to be explicitly set for Jaeger Exporter

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#1191] opened 2020-06-25 13:51 UTC
**Describe the bug**
After ca99122ca84642543f1333c32ba28fecdb4860b3, Jaeger server reports the following when a regular OpenTelemetry Collector attempts to establish a gRPC connection:

```
{"level":"warn","ts":1593090096.5975018,"caller":"grpc@v1.27.1/server.go:669","msg":"grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\t\\\\x01\\\\x00\\\\x01\\\\x05\\\\x03\\\\x03\\\\xde\\\\xe1RP\\\\xc1>\\\\x19<\\\\xb4\\\\xc7{\\\\x0f\\\\xaf\\\"\"","system":"grpc","grpc_log":true}
```

**Steps to reproduce**

The following YAML file is enough to reproduce the issue on the current master, provided that Jaeger Collector is running on localhost:
```yaml
receivers:
  otlp:

processors:
  batch:

exporters:
  jaeger:
    endpoint: "localhost:14250"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```

I'm running OpenTelemetry from `master` with `make run`. I was able to reproduce it with the tag v0.4.0.

I'm running Jaeger also from `master`, with `$ go run ./cmd/all-in-one/main.go --query.static-files jaeger-ui/packages/jaeger-ui/build` but I was able to reproduce the same with the image `jaegertracing/all-in-one:1.18`.

**What did you expect to see?**
No errors on the Jaeger side when connecting to it.

**What did you see instead?**

The following message on the Jaeger side:
```
{"level":"warn","ts":1593090225.1251826,"caller":"grpc@v1.27.1/server.go:669","msg":"grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\t\\\\x01\\\\x00\\\\x01\\\\x05\\\\x03\\\\x03\\\\x9d\\\\x1c\\\\xb3\\\\v\\\\xe3\\\\x9dǵepp\\\\xe5)\\\"\"","system":"grpc","grpc_log":true}
```

**What version did you use?**
Version: master as of now (`4eca960a4eb02104694324cf161ad9ec944c44c9`)

**What config did you use?**
Config: see above

**Environment**
OS: Fedora 32 w/ the latest updates
Compiler(if manually compiled): `go1.14.3`

**Additional context**
Known workaround: explicitly adding `insecure: true` to the receiver settings bypasses this problem. Here's a configuration file that works:

```yaml
receivers:
  otlp:

processors:
  batch:

exporters:
  jaeger:
    endpoint: "localhost:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```

**Comment by jpkrohling** [comment] 2020-06-26 11:52
Same with the OTLP exporter.

**Comment by jrcamp** [comment] 2020-07-21 16:14
@jpkrohling I believe TLS settings were intentionally switched to be enabled by default so it's expected you'd have to disable it if your server doesn't have TLS enabled.

**Comment by jpkrohling** [comment] 2020-07-22 10:24
Not sure it makes sense: if a cert and key aren't provided as part of the configuration, how can the listener be configured with TLS?

**Comment by jrcamp** [comment] 2020-07-22 15:27
> Not sure it makes sense: if a cert and key aren't provided as part of the configuration, how can the listener be configured with TLS?

I haven't dug into the jaegar specifics but in general for TLS clients certs and keys are all optional. (This is different than TLS servers where a cert and key _are_ always required). For clients it should using [system CA](https://golang.org/pkg/crypto/x509/#SystemCertPool) if available to populate CA certs. If a valid CA is in there for the server you're connecting to then the connection should work (assuming you're not using client auth). If you are using client auth then yes those settings would be required.

Whether or not jaegar/grpc is doing this (using SystemCertPool) by I can't tell from a quick grep of the code.

**Comment by jpkrohling** [comment] 2020-07-22 15:38
You are absolutely right, I had the server in mind, but client is the right context here!

**Comment by jrcamp** [comment] 2020-07-23 22:01
I think it's functioning as intended then, please correct if I'm missing anything. Closing.

**Closed by jrcamp** 2020-07-23 22:01 UTC
Labels: bug
