### ISSUE TITLE
Ability to set maximum batch size

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#1020] opened 2020-05-26 11:23 UTC
**Is your feature request related to a problem? Please describe.**

[Batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#batch) allows to specify a minimum size of the batch or timeout. When either is exceeded, the batch of collected spans is sent down the stream. This ensures that a "compressed" package of data is being processed and exported, rather than doing it one-by-one span (in the worst scenario).

In certain circumstances, the opposite happens. There might be a large chunk of spans incoming,  which is actually larger than what is the expected limit of the exported batch. Currently there is no way (to my best knowledge) to break those massive incoming batches into smaller ones.

**Describe the solution you'd like**

Having an ability to set an upper bound of the batch size (e.g. configured as `send_batch_hard_limit`). The default value can be `0` - which means no upper limit.

**Describe alternatives you've considered**

It would be possible to set this limit in an exporter, though making it as an extension of the batch processor is a more generic solution that would work with any exporter underneath

**Additional context**

I have built a working prototype of that. If it's something that is considered an useful feature and would make sense to be included as part of `batch_processor` (or in any other way) - I will be happy to open a PR

**Comment by pmm-sumo** [comment] 2020-05-26 11:26
For reference, here's the prototype: https://github.com/pmm-sumo/opentelemetry-collector/pull/2

**Comment by tigrannajaryan** [comment] 2020-05-27 18:12
I am not sure proposed https://github.com/pmm-sumo/opentelemetry-collector/pull/2 implementation is a good approach. With this proposal the batcher will do its usual logic and will wait until send_batch_size is accumulated or timeout is passed and then will begin splitting the batch into smaller ones if send_batch_hard_limit is smaller than the accumulated batch. A better approach would be to check for send_batch_hard_limit before the batch is accumulated and send it immediately. This would reduce the delay introduced by the batched (which is only necessary if you need to accumulate but pointless if you need to split).

**Comment by pmm-sumo** [comment] 2020-05-27 18:34
> if send_batch_hard_limit is smaller than the accumulated batch

You are right @tigrannajaryan , I have assumed (and missed including it in the docs) that `send_batch_hard_limit` should be always larger than `send_batch_size` (in my environment I set it to 2x `send_batch_size`). With the check in place (essentially `send_batch_size` becoming `min(send_batch_size, send_batch_hard_limit)`) would it make sense to open a PR?

**Comment by bogdandrutu** [comment] 2020-07-13 22:12
@pmm-sumo I think https://github.com/open-telemetry/opentelemetry-collector/pull/1310 fixes this.

I will close this as a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/1140, if you think you need a bit more than https://github.com/open-telemetry/opentelemetry-collector/issues/1140 please comment there.

**Closed by bogdandrutu** 2020-07-13 22:12 UTC
Labels: feature request
