### ISSUE TITLE
Support hot deployment

### ISSUE THREAD

**Issue by huangtc-github** [open-telemetry/opentelemetry-collector#11269] opened 2024-09-25 06:44 UTC
Support hot deployment of configuration changes without restarting the OpenTelemetry Collector.

**Comment by codeboten** [comment] 2024-09-25 15:29
Thanks @huangtc-github, please see https://github.com/open-telemetry/opentelemetry-collector/issues/5966 for additional details around this topic. Marking this closed as a duplicate of that issue to keep the discussion in a single place

**Closed by codeboten** 2024-09-25 15:29 UTC

**Comment by huangtc-github** [comment] 2024-09-26 01:32
I used the --enable-hot-reload command as per the issue, but it returned an error stating that the parameter is not supported:

Error: unknown flag: --enable-hot-reload
2024/09/26 09:31:00 collector server run finished with error: unknown flag: --enable-hot-reload
