### ISSUE TITLE
[exporters/sending_queue] add block option in sending_queue

### ISSUE THREAD

**Issue by yutingcaicyt** [open-telemetry/opentelemetry-collector#7423] opened 2023-03-24 06:53 UTC
**Is your feature request related to a problem? Please describe.**
Sending_queue decouples data processing and sending very well. When the queue is full, the only option now is to drop the data directly, however, sometimes I don't want to drop the data but slow down or stop the collection until the queue is free again. Especially when I read the log from a file, blocking the queue will not cause data loss, but only increase the delay of data.

**Describe the solution you'd like**
Add block option when the send_queue is full.

**Comment by yutingcaicyt** [comment] 2023-03-24 06:54
@mx-psi @bogdandrutu

**Comment by tanner-bruce** [comment] 2023-06-23 02:11
duplicate https://github.com/open-telemetry/opentelemetry-collector/issues/5456

When using a pubsub receiver which calls the pipeline from multiple goroutines this would be extremely helpful.

**Comment by mx-psi** [comment] 2023-06-26 10:35
Agreed that this is a duplicate of #5456, closing as such

**Closed by mx-psi** 2023-06-26 10:35 UTC
