### ISSUE TITLE
Using windows reserved port

### ISSUE THREAD

**Issue by joshmouch** [open-telemetry/opentelemetry-collector#8683] opened 2023-10-13 19:53 UTC
When trying to use zpages in OTEL collector, it attempts to access port 55679.  In windows, this is a reserved port that cannot be used.

Try running this:
netsh int ipv4 show excludedportrange protocol=tcp

**Comment by pjanotti** [comment] 2023-10-14 00:19
The port is in the dynamic range so it possible that some configuration already took it or is blocking its usage, but, that isn't reserved by default on Windows AFAIK. On a brand new Azure Windows 2022 VM I can ran de collector using the default port for zpages without issues. Same on my Windows 10 box. That said it is typical that organizations or security software exclude many ports on the dynamic range.

**Comment by mx-psi** [comment] 2023-10-17 11:46
@joshmouch Can you clarify if your setup differs from @pjanotti's in some significant way?

**Comment by mx-psi** [comment] 2023-10-30 09:50
I am going to close this as can't reproduce for now. @joshmouch if you have anything that can help us reproduce this please comment on this issue and I will reopen

**Closed by mx-psi** 2023-10-30 09:50 UTC
Labels: bug, extension/zpages, os:windows
