### ISSUE TITLE
If the link exceeds 1 minute, there will be discontinuity, resulting in incorrect time.

### ISSUE THREAD

**Issue by yunzck8s** [open-telemetry/opentelemetry-collector#9339] opened 2024-01-23 00:43 UTC
There is a time difference of about 4 seconds or higher between my multiple kubernetes nodes. Then when I check the link in grafana tempo, there are generally many interrupted links in the trance of more than 1 second. I suspect that the server time difference causes this interruption.

My OpenTelemetryCollector configuration:
```
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: syncplant-backend
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: http://10.128.14.49:32621
        tls:
          insecure: true
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,otlp]

![297278511-4f2f95be-9c77-4d33-adda-37222b926e78](https://github.com/open-telemetry/opentelemetry-collector/assets/86189975/116e862b-cbd9-4b86-9146-8f7164153b32)

**Comment by yunzck8s** [comment] 2024-01-23 00:43
![297278511-4f2f95be-9c77-4d33-adda-37222b926e78](https://github.com/open-telemetry/opentelemetry-collector/assets/86189975/89960d83-4391-4167-93d6-6e03f63219d2)

**Comment by mx-psi** [comment] 2024-01-23 11:14
Hi @yunzck8s, this seems like an issue in your backend (in this case Grafana). I suggest you reach out on any of the ways listed over at https://grafana.com/help/ to get help with this, this issue tracker is focused on OpenTelemetry Collector issues. Do you have any reason to believe your issue is related to the OpenTelemetry Collector specifically?

**Comment by yunzck8s** [comment] 2024-01-25 08:09
@mx-psi I don't think there is any problem with OpenTelemetry Collector, thank you for your help, I think I should look for help in grafana

**Comment by mx-psi** [comment] 2024-01-25 10:05
Okay! I will cc @jpkrohling here just in case there is a better link to share with you but otherwise I am going to close this as not planned since we won't be able to help you here :)

**Closed by mx-psi** 2024-01-25 10:05 UTC
Labels: question, waiting-for-author

**Comment by electron0zero** [comment] 2024-01-25 12:13
Hi @yunzck8s , I see that you mentioned tempo in this issue. 

I looked at the issue it and it doesn't have enough info for me to debug or reproduce.

can you file a detailed issue into [tempo](https://github.com/grafana/tempo/issues) or [grafana ](https://github.com/grafana/grafana/issues) repo with more information and step to reproduce this issue, and we can dig into it :)

**Comment by yunzck8s** [comment] 2024-01-26 04:47
@electron0zero No problem, thank you for your attention.
