### ISSUE TITLE
Some proto files are not in sync with opentelemetry-proto-go repository

### ISSUE THREAD

**Issue by MWalcz4k** [open-telemetry/opentelemetry-collector#3754] opened 2021-08-02 12:37 UTC
**Describe the bug**
Proto-go repository has a comment that [this field](https://github.com/open-telemetry/opentelemetry-proto-go/blob/5d7297e2f56b4e5cf29b753f33bcd14ad6b4452f/otlp/metrics/v1/metrics.pb.go#L1135) is supposed to be depricated but it is still in use in the collector [here](https://github.com/open-telemetry/opentelemetry-collector/blob/3c99398c27e57bc0702ad9e49a105c2d23f8d238/model/internal/data/protogen/metrics/v1/metrics.pb.go#L994). Additionally the whole file is not in sync with what can be found in proto repository. Are labels really deprecated, which proto should I use and if removing labels is coming to the collector when can I expect this to happen?

**Steps to reproduce**
Look at code

**What did you expect to see?**
Attributes instead of Labels. I would also expect those two proto files to be in sync or maybe imported at all because I can't see proto-go repo used in go.mod anywhere.

**What did you see instead?**
Labels instead of Attributes

**What version did you use?**
Newest versions

**What config did you use?**
Not applicable

**Environment**
Not applicable

**Additional context**
Not needed

**Comment by bogdandrutu** [comment] 2021-08-02 18:23
Duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/3535

**Closed by bogdandrutu** 2021-08-02 18:23 UTC
Labels: bug
